### ISSUE TITLE
Tracktor for One Stage Detector

### ISSUE THREAD

**Issue by yonafalinie** [open-mmlab/mmtracking#107]
Hai

Thank you for the hard work.
I was just wondering if there is any future support for one-stage detector in Tracktor?

**Comment by OceanPang** [comment]
@yonafalinie Supported in #113 , you can try to modify the config of the detector to some single stage detectors. Let me know if you still have any problems.

**Comment by yonafalinie** [comment]
Thank you so much for the reply. I did modify the config of the detector.
However in tracktor_tracker.py inside folder trackers line 65 it still accepting 'roi_head',
or maybe there are something that i missed?

**Comment by OceanPang** [comment]
I will fix this issue in the next PR.

**Comment by yonafalinie** [comment]
Thanks!. Much appreciated.

**Comment by OceanPang** [comment]
Hi @yonafalinie, I found that Tracktor cannot support single-stage detectors. 
As [here](https://github.com/open-mmlab/mmtracking/blob/dc367868453fdcb528041176a59ede368f0e2053/mmtrack/models/mot/trackers/tracktor_tracker.py#L57), Tracktor uses the RoIHead in two-stage detectors to regress the objects to the next frame. As single-stage detectors such as RetinaNet do not support bounding boxes input, they are incompatible with Tracktor.
