### ISSUE TITLE
Details of Tracktor

### ISSUE THREAD

**Issue by Leo63963** [open-mmlab/mmtracking#109]
Hi!
For the results of Tracktor, have you used Interpolation for the results?
Thanks

**Comment by OceanPang** [comment]
Hi, what do you mean by `Interpolation for the results`?

**Comment by Leo63963** [comment]
Hi！
Thanks for the reply.
I mean, when tracking (MOT), some targets are re-identified, and have you interpolated the boxes between them?

**Comment by OceanPang** [comment]
No, we do not interpolate these disappeared objects.

**Comment by Leo63963** [comment]
Thanks for the reply.
