### ISSUE TITLE
Difference between tractor in mmtrack and the original tractor implementation.

### ISSUE THREAD

**Issue by haak0** [open-mmlab/mmtracking#116]
Hi, as is reported in model zoo, the tractor here outperforms the original tractor by a large margin. 
![image](https://user-images.githubusercontent.com/7685361/110583984-7b1ebc00-81a9-11eb-8426-ccf7ce18d192.png)
I'm wondering what differences made the improvements.

<del>I also tried to remove the reid module in tractor, and the MOTA metric does not change at all when ID switches increase, I do not know why, do you have any ideas? </del>

**Comment by OceanPang** [comment]
Hi @haak0, for the first question, please refer to #67 .

For the second question, can you post the configs and screenshots of your results here?

**Comment by haak0** [comment]
hi, I retried and found that MOTA decreased a little bit. Question 2 is due to my misuse of mmtrack config file. Thanks.
