### ISSUE TITLE
Where to get testing_set.txt about lasot?

### ISSUE THREAD

**Issue by kuiran** [open-mmlab/mmtracking#118]
My dataset doesn't have the file testing_set.txt , where to get it ?Thanks lot.

**Comment by GT9505** [comment]
Here is the [download page](http://vision.cs.stonybrook.edu/~lasot/download.html) of LaSOT. You can download LaSOTTesting.zip from [GoogleDrive](https://bit.ly/LaSOTTest), [Baidu Pan](https://pan.baidu.com/s/1KBlrWGOFH9Fe85pCWN5ZkA&shfl=sharepset), or [local](http://vision.cs.stonybrook.edu/~lasot/data/LaSOTTesting.zip). The LaSOTTesting.zip contains testting_set.txt.
