### ISSUE TITLE
error in documentation to fix demo command

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmtracking#120]
There is an error in the demo command, here [at install ](https://github.com/open-mmlab/mmtracking/blob/master/docs/install.md#verification)
 When I run the demo using command, 

`python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py -i demo/demo.mp4 -o mot.mp4
`
I get the error below:

```
usage: demo_mot.py [-h] [--input INPUT] [--output OUTPUT] [--checkpoint CHECKPOINT] [--device DEVICE] [--show] [--backend {cv2,plt}] [--fps FPS] config
demo_mot.py: error: unrecognized arguments: -i demo/demo.mp4 -o mot.mp4
```

This is fixed by changing the input slightly 
`python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4`

**Comment by OceanPang** [comment]
Thanks for your report. Fixed in #121 .
