### ISSUE TITLE
demo where I run on my own bounding boxes

### ISSUE THREAD

**Issue by nikky4D** [open-mmlab/mmtracking#127]
Is there a demo where I can implement tracking on my own bounding boxes for the case of multiobject tracking?

I have my own detector that returns bounding boxes and the confidences for the boxes. I want to use mmtracking to do the tracking but I'm not sure how to instantiate the tracker, and run on my own boxes. Is there a demo I can use for that?

**Comment by OceanPang** [comment]
Hi @nikky4D, you can follow the configs of the models with "public_bboxes" on the MOT benchmark, like [this](https://github.com/open-mmlab/mmtracking/blob/master/configs/mot/deepsort/deepsort_faster-rcnn_fpn_4e_mot17-public-half.py). That is, you can try to convert your detection results in a pkl file. 
Let me know if you need more details.

**Comment by nikky4D** [comment]
Thank you. I don't think I can make the conversion to .pkl file as I am doing an online realtime application. But can I just build the test pipeline for a single images following your example? And from your example, I understand most of what needs to happen to a single image except for the last line. what does this line do:  `dict(type='VideoCollect', keys=['img', 'public_bboxes']`

**Comment by OceanPang** [comment]
This line collects the tensors in the data pipeline and feed the `img` and `public_bboxes` to the model.

**Comment by nikky4D** [comment]
Thank you.

**Comment by imtarit** [comment]
Hi @OceanPang ,

I am working with a custom image dataset and instance segmentations generated using Mask R-CNN from MMDetection. I followed your configuration and data conversion instructions but encountered an error.

Custom Dataset Directory Structure:

```css
Workspace\
----Dataset\
--------img1.png
--------img2.png
--------annotations\half-val_detections.pkl
```

I transformed the MMDetection output into a dictionary as follows:

```json
{
    "image1_name": [MMDetection output as dict],
    "image2_name": [MMDetection output as dict],
    ...
}
```

Configuration:
```python
_base_ = ['./deepsort_faster-rcnn_fpn_4e_mot17-private-half.py']
data_root = 'workspace/Dataset/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadDetections'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1088, 1088),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='VideoCollect', keys=['img', 'public_bboxes'])
        ])
]
data = dict(
    val=dict(
        detection_file=data_root + 'annotations/half-val_detections.pkl',
        pipeline=test_pipeline),
    test=dict(
        detection_file=data_root + 'annotations/half-val_detections.pkl',
        pipeline=test_pipeline))
```

Error Traceback:

```plaintext
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "workspace\lib\mmtracking\tools\test.py", line 236, in <module>
    main()
  File "workspace\lib\mmtracking\tools\test.py", line 151, in main
    dataset = build_dataset(cfg.data.test)
  File "workspace\.venv_2\lib\site-packages\mmdet\datasets\builder.py", line 82, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "workspace\.venv_2\lib\site-packages\mmcv\utils\registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: MOTChallengeDataset: [Errno 2] No such file or directory: 'data/MOT17/annotations/half-val_cocoformat.json'
```
I would appreciate your guidance on what might be going wrong here.
