### ISSUE TITLE
How to obtain the Reid feature using mmtracking?

### ISSUE THREAD

**Issue by WingsleyLui** [open-mmlab/mmtracking#132]
Hi, thanks for the neat work!

I noted that some of the tracking models include the Reid model(e.g. deepsort_faster-rcnn_fpn_4e_mot17-private-half.py). how can I obtain the Reid feature for the person being tracked?

**Comment by yonafalinie** [comment]
Hi, mmtracking directly use the ReID model from Tracktor 
[https://github.com/phil-bergmann/tracking_wo_bnw](url) 
Therefore we have to train the Reid features from here then we can further use it for tracking.
