### ISSUE TITLE
About comment

### ISSUE THREAD

**Issue by Leo63963** [open-mmlab/mmtracking#134]
Hi
I think the: 
https://github.com/openmmlab/mmtracking/blob/0055947c4d19c8921c32ce128ae0314d61e593d2/mmtrack/models/mot/trackers/tracktor_tracker.py#L17

maybe you mean for _regression_ model. Since the ReID exists behind.

Is that true? 
Thanks

**Comment by OceanPang** [comment]
Hi @Leo63963 , I cannot open the link you shared.

**Comment by Leo63963** [comment]
Hi @OceanPang 
Sorry for the link.
I mean the _mmtrack/models/mot/trackers/tracktor_tracker.py_, line 17, the comment.
It refers to reid, I personally think it might be regression model.
Thanks.

**Comment by OceanPang** [comment]
@Leo63963 Leo，thanks for your point out. We will fix it soon.
