### ISSUE TITLE
How to actually Train with mmtracking (e.g MOT)

### ISSUE THREAD

**Issue by leemengwei** [open-mmlab/mmtracking#138]
I'm following tutorial:
**Training on a single GPU
python tools/train.py ${CONFIG_FILE} [optional arguments]**
then I tried:
python tools/train.py configs/mot/deepsort/deepsort_faster-rcnn_fpn_4e_mot17-public-half.py
it gives me:
_NotImplementedError: Please train `detector` and `reid` models first and                 inference with Tracktor._

Can you give me some advice? Thanks!

**Comment by leemengwei** [comment]
Ok， I got it. I should train with MMDetection, then use this trained model (denoted as 'detector' in MMTrack) in MMT's config file. Thanks anyway

**Comment by leemengwei** [comment]
> I'm following tutorial:
> **Training on a single GPU python tools/train.py ${CONFIG_FILE} [optional arguments]**
> then I tried:
> python tools/train.py configs/mot/deepsort/deepsort_faster-rcnn_fpn_4e_mot17-public-half.py
> it gives me:
> _NotImplementedError: Please train `detector` and `reid` models first and inference with Tracktor._
> 
> Can you give me some advice? Thanks!

Also, I guess ' inference with Tracktor', the 'Tracktor' here not actually means configuration file under configs/mot/tracktor/*.py right? It means any py like deepsort's sort*.py and deepsort*.py. If I'm wrong,  do notice me~

**Comment by leemengwei** [comment]
> Ok， I got it. I should train with MMDetection, then use this trained model (denoted as 'detector' in MMTrack) in MMT's config file. Thanks anyway

Alright, here for train using mmtracking:
[https://github.com/open-mmlab/mmtracking/blob/3ceb8e40293bf007a765c0659e4306ce70be1194/configs/det/README.md](url)

**Comment by rvrsprdx** [comment]
Hi,

can you elaborate on how you got the training of a MOT method working?
For example for DeepSort: I don't think it is sufficient to only train a detector with MMDetection and pass it to MMTracking's config file because the Appearance Descriptor of DeepSort has to be trained as well, right?

I'd appreciate some help. Thanks.

**Comment by castrovictor** [comment]
> Hi,
> 
> can you elaborate on how you got the training of a MOT method working? For example for DeepSort: I don't think it is sufficient to only train a detector with MMDetection and pass it to MMTracking's config file because the Appearance Descriptor of DeepSort has to be trained as well, right?
> 
> I'd appreciate some help. Thanks.

They use another appearance descriptor, but yes, it has to be trained. Check [this](https://github.com/open-mmlab/mmtracking/issues/132) and [this]([https://github.com/phil-bergmann/tracking_wo_bnw](https://github.com/open-mmlab/mmtracking/issues/url))
