### ISSUE TITLE
The person's id will change when the person is covered by other people or things

### ISSUE THREAD

**Issue by MichaelWU0726** [open-mmlab/mmtracking#140]
Hi, thanks for your work! I had a trouble in track people using MOT model. When the person tracked was covered by other people or things，the person's id would change later. I don't know whether was caused by MOT model itself. Could you improve the model in near future，thanks.

**Comment by OceanPang** [comment]
Hi @MichaelWU0726, this is because the MOT model is not always accurate. 
We will try to improve the performance of the MOT model and include more MOT models.
