### ISSUE TITLE
batch support

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmtracking#141]
When are you planning to add support for performing training and inference in batches?

**Motivation**
It would increase the training and inference speeds a lot.

**Comment by GT9505** [comment]
In video-related tasks, batch testing means each gpu processes several videos simultaneously. We need copy these videos with different duration to the same duration. We don't have enough time to support it right now, but the PRs from the community are welcome.

**Comment by fcakyon** [comment]
I see, thanks for your feedback.
