### ISSUE TITLE
the reason why imagenet_det_30plus1cls.json needed

### ISSUE THREAD

**Issue by kwon852456** [open-mmlab/mmtracking#149]
hello.
I'm very thank you for your nice work.

I wonder why image-net detection dataset is needed when I want to train video object detection models such as FGFA.

I prepared Image-net VID dataset and converted it to coco-Vid format but couldn't train my custom model properly since I don't have "imagenet_det_30plus1cls.json" file.

Is there any way to train my custom vid-model without detection dateset?

In my opinion, the vid dataset already have bounding boxes for objects, so object detection dataset is not nessarary.

thank you for reading and hope this Issue can help others.

**Comment by OceanPang** [comment]
It is a common practice that the VID papers use the ImagetNet DET dataset to jointly train with the VID set to avoid the overfitting problem. You can download the DET set and convert the annotations according to our [script](https://github.com/open-mmlab/mmtracking/blob/master/tools/convert_datasets/imagenet2coco_det.py).
