### ISSUE TITLE
Customize dataset with CocoVideoDataset style has issue

### ISSUE THREAD

**Issue by LEE-cm** [open-mmlab/mmtracking#152]
this link: https://mmtracking.readthedocs.io/en/tests/assets/demo_cocovid_data/ann.json is invalid
I converted my datasets to the specified format as required, but I couldn't run the program, and the official example ann.json is can't available

**Comment by OceanPang** [comment]
Hi @LEE-cm, the json is located [here](https://github.com/open-mmlab/mmtracking/blob/master/tests/assets/demo_cocovid_data/ann.json).
Please refer to the file and let me know if you have any problems.
