### ISSUE TITLE
how to get the value in prepare_train_imgs() of mmdet/custom.py?

### ISSUE THREAD

**Issue by lymoon3129** [open-mmlab/mmtracking#153]
hello!
Since I want to change the way of data loading, I tried to modify the prepare_train_imgs() and prepare_test_imgs() . However, I found that I can't step in these two functions. 
Could you give me some advice?

Thanks

**Comment by OceanPang** [comment]
Can you be more specific in your questions?
What's the meaning of `can't step in`?
