### ISSUE TITLE
What are the supported detectors of tracktor? tried Cascade-RCNN, but failed.

### ISSUE THREAD

**Issue by Tyushang** [open-mmlab/mmtracking#159]
Hi, i want to try some detectors(e.g. detectors in mmdetection) other than faster-rcnn in tracktor,  but I got error when change it to Cascade-RCNN. details:
### 1: Modify tracktor_faster-rcnn_r50_fpn_4e_mot17-private-half.py to point Cascade-RCNN config:
```
USE_MMDET = True

_base_ = [
    '../../_base_/models/cascade_rcnn_r50_fpn.py',
    '../../_base_/datasets/mot_challenge.py', '../../_base_/default_runtime.py'
]
model = dict(
    type='Tracktor',
    pretrains=dict(
        detector=  # noqa: E251
        'http://download.openmmlab.com/mmdetection/v2.0/cascade_rcnn/cascade_rcnn_r50_fpn_1x_coco/cascade_rcnn_r50_fpn_1x_coco_20200316-3dc56deb.pth',  # noqa: E501
        reid=  # noqa: E251
        'https://download.openmmlab.com/mmtracking/mot/reid/tracktor_reid_r50_iter25245-a452f51f.pth'  # noqa: E501
    ),
    # detector=dict(
    #     rpn_head=dict(bbox_coder=dict(clip_border=False)),
    #     roi_head=dict(
    #         bbox_head=dict(bbox_coder=dict(
    #             clip_border=False), num_classes=1))),
...
```
### 2: Run command:
```
python demo/demo_mot.py  ../configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py \
          --input /home/lmd/dataset/lmd-sample/e683e103df4e8902c5b77042919b8361.mp4 \
          --fps 30  --output /home/lmd/output/mmtracking.mp4
```
### 3: Got the following error:
```
...
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/mmtrack/apis/inference.py", line 92, in inference_mot
    result = model(return_loss=False, rescale=True, **data)
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 95, in new_func
    return old_func(*args, **kwargs)
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/mmtrack/models/mot/base.py", line 154, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/mmtrack/models/mot/base.py", line 131, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/mmtrack/models/mot/tracktor.py", line 119, in simple_test
    rescale=rescale)
  File "/home/lmd/anaconda3/lib/python3.7/site-packages/mmdet/models/roi_heads/test_mixins.py", line 108, in simple_test_bboxes
    bbox_results = self._bbox_forward(x, rois)
TypeError: _bbox_forward() missing 1 required positional argument: 'rois'
```

I find out that, the runtime CascadeRoIHead._bbox_forward(self, stage, x, rois) requires 3 args, but only 2 given, missing arg stage, I wonder if it is possiable to config Cascade-RCNN as detector of tracktor? How to config if it is possible? and What are the supported detectors of tracktor?

Any help will be appreciated, thank you!

**Comment by OceanPang** [comment]
Hi, currently tracktor only support two-stage detectors like Faster R-CNN, you can try other detectors. 

We will consider whether we can support Cascade R-CNN in the future.

**Comment by yonafalinie** [comment]
Hi, I am also encounter same error while using Cascade R-CNN on Deepsort. Is it right to assume that both Tracktor and Deepsort cannot support Cascade R-CNN as of now?

**Comment by TheRealPoseidon** [comment]
> Hi, I am also encounter same error while using Cascade R-CNN on Deepsort. Is it right to assume that both Tracktor and Deepsort cannot support Cascade R-CNN as of now?

Hi yona, l am also trying to use Cascade R-CNN as the detector in Deepsort. Do you have any advise? Thanks and best regards.

**Comment by GT9505** [comment]
Hi, @Tyushang @yonafalinie @TheRealPoseidon 

Currently, Tracktor and DeepSORT don't support Cascade R-CNN.

If you want to use Cascade R-CNN in Tracktor, you need to change `self.detector.roi_head.simple_test_bboxes()` to `self.detector.roi_head.simple_test()` in [Line 119](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/models/mot/tracktor.py#L119), since `simple_test()` is a more general function. The corresponding code of DeepSORT is in [Line 99](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/models/mot/deep_sort.py#L99).

Please also note that the output type between `simple_test_bboxes()`  and `simple_test()` is different. You need to adapt the code by yourself, and it's not very complex.

By the way, it would be very appreciated if you could create a PR to support Cascade R-CNN in Tracktor and DeepSORT.

**Comment by Tyushang** [comment]
Thank you very much @GT9505 , I'd like to create a PR, but right now I'm too busy to do so cuz there's lots of work to do, I will create a PR if I have spare time.
