### ISSUE TITLE
reID model using mmclassification?

### ISSUE THREAD

**Issue by taofuyu** [open-mmlab/mmtracking#163]
To use mmtracking for other missions, re-train ReID model is important. But as you mentioned in configs/mot/deepsort/README.md, "Currently we do not support training ReID models."
But, in the code, the class BaseReID is derived from ImageClassifier. So, is it possible to use mmclassification to train a ReID model ? And use it in mmtracking?
Thanks a lot.

**Comment by OceanPang** [comment]
Hi @taofuyu, this feature is under implementation and shall be supported at the end of this month (maybe delayed by several days). Thanks.

**Comment by taofuyu** [comment]
> Hi @taofuyu, this feature is under implementation and shall be supported at the end of this month (maybe delayed by several days). Thanks.

Thanks your remarkable work
