### ISSUE TITLE
Is there any pretrained model for MOT task on different categories?

### ISSUE THREAD

**Issue by dawnlh** [open-mmlab/mmtracking#165]
Hi~ Thanks for the wonderful tool!
It seems that the provided pretrained models (deepsort and tracktor) for MOT can only figure out pedestrians, so is there any model that can deal with more categories, like car, bicycle and so on?

**Comment by GT9505** [comment]
Since MOT dataset is the polular dataset of MOT field and only contains the category of person, the provided pertrained models can only track person. We will add dataset with more diverse categories, such as TAO, in the future.

**Comment by dawnlh** [comment]
Thanks! looking forward to new pretrained models~
