### ISSUE TITLE
Errors with mmdetection version v2.12.0 and mmtracking v0.5.1

### ISSUE THREAD

**Issue by wongsinglam** [open-mmlab/mmtracking#168]
Hi,

I met the problem:

cannot import name 'Fp16OptimizerHook' from 'mmdet.core'

When the mmdetection version is v2.12.0 and mmtracking version is v0.5.1.

But when I used master branches of both, it worked fine.

**Comment by OceanPang** [comment]
Hi @wongsinglam, this bug should be fixed before. Can you confirm the version of your mmdetection and mmcv?

**Comment by wongsinglam** [comment]
Hi, thank you for your reply. The version of mmcv is 1.3.5 while mmdetection is v2.12.0 seen as in the title. Hope it is useful to you.

**Comment by wychappy** [comment]
'Fp16OptimizerHook' is not in mmdet.core, I change 'from mmdet.core import Fp16OptimizerHook' into 'from mmcv.runner.hooks.optimizer import Fp16OptimizerHook' can solve the problem.The version of mmcv is 1.3.8 while mmdetection is v2.14.0

**Comment by OceanPang** [comment]
We already provide the compatible versions of mmcv and mmdet in the [docs](https://github.com/open-mmlab/mmtracking/blob/master/docs/install.md).

Let us know if there are still problems.
