### ISSUE TITLE
Train reID model in mmtracking

### ISSUE THREAD

**Issue by taofuyu** [open-mmlab/mmtracking#169]
When will release this feature?Thanks

**Comment by ToumaKazusa3** [comment]
Hi~It will be added to version 0.6.0, which will be released at the end of June, 2021.

**Comment by taofuyu** [comment]
> June

Thanks

**Comment by ToumaKazusa3** [comment]
We have supported the training process of ReID model in mmtracking. You can use the [config](https://github.com/open-mmlab/mmtracking/blob/master/configs/reid/resnet50_b32*8_MOT17.py) to train your own ReID model, or directly use the [pretrain model](https://download.openmmlab.com/mmtracking/mot/reid/reid_r50_6e_mot17-4bf6b63d.pth) .
