### ISSUE TITLE
ModuleNotFoundError: No module named 'motmetrics.math_util'

### ISSUE THREAD

**Issue by chengzhixing** [open-mmlab/mmtracking#173]
i install the motmetrics==1.1.3, but no module named 'motmetrics.math_util'. which version have the module?

**Comment by OceanPang** [comment]
Can you try the latest version of motmetrics?

**Comment by chengzhixing** [comment]
> Can you try the latest version of motmetrics?

thanks, i just solved it by https://github.com/cheind/py-motmetrics
