### ISSUE TITLE
SOT not working as expected

### ISSUE THREAD

**Issue by callzhang** [open-mmlab/mmtracking#184]
Thanks for your error report and we appreciate it a lot.

**Checklist**

[x] I have searched related issues but cannot get the expected help.
[x] The bug has not been fixed in the latest version.

**Describe the bug**
Using the `demo_sot.py` script, and draw the bbox on the female on the right, I got unexpected results:

https://user-images.githubusercontent.com/5102827/123091679-39660880-d45c-11eb-85c3-971767dd8de6.mp4

**Reproduction**

1. What command or script did you run?

```none
demo_sot.py
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?  -> changed the input and output path
3. What dataset did you use and what task did you run? -> None

**Comment by ToumaKazusa3** [comment]
hi~ what command did you run? I think you may not use the pretrain model. If you use it, please give me your demo download link.

**Comment by callzhang** [comment]
I used the baseline DLA model "fairmot_dla34.pth" provided in the repo.

**Comment by callzhang** [comment]
Here is the args in `demo_sot.py` I used:
```

def main():
    parser = ArgumentParser()
    parser.add_argument(
        '--config', default='configs/sot/siamese_rpn/siamese_rpn_r50_1x_lasot.py', help='Config file')
    parser.add_argument('--input', default='demo/video_10s.mp4',
        help='input video file')
    parser.add_argument('--output', default='output/sot.mp4', help='output video file (mp4 format)')
    parser.add_argument('--checkpoint', help='Checkpoint file')
    parser.add_argument(
        '--device', default='cuda:0', help='Device used for inference')
    parser.add_argument(
        '--show',
        action='store_false',
        default=True,
        help='whether to show visualizations.')
    parser.add_argument(
        '--color', default=(0, 255, 0), help='Color of tracked bbox lines.')
    parser.add_argument(
        '--thickness', default=3, type=int, help='Thickness of bbox lines.')
    args = parser.parse_args()
    args.device = 'cpu'
```

**Comment by ToumaKazusa3** [comment]
I think you should set a pretrain model in `--checkpoint`.

**Comment by ToumaKazusa3** [comment]
You can try following command:
`python ./demo/demo_sot.py \
    ./configs/sot/siamese_rpn/siamese_rpn_r50_1x_lasot.py \
    --input demo/video_10s.mp4 \
    --checkpoint ../mmtrack_output/siamese_rpn_r50_1x_lasot_20201218_051019-3c522eff.pth \
    --output output/sot.mp4 \
    --show`

**Comment by callzhang** [comment]
Thanks a lot! That solved it. I saw there is model to be downloaded at the begining and I thought the model file was automatically downloaded.
