### ISSUE TITLE
ResNet101 for Tracktor method

### ISSUE THREAD

**Issue by ssyou** [open-mmlab/mmtracking#187]
Hi~ Thanks for the wonderful tool!
Have you tested the performance with resnet101 for the MOT task?
Could you provide the pre-trained model with ResNet101 for MOT(Tracktor) method?

**Comment by ToumaKazusa3** [comment]
Do you mean to replace the detector's backbone with `ResNet101` in `Tracktor`?

**Comment by ssyou** [comment]
YES

**Comment by ToumaKazusa3** [comment]
We do not have pre-trained model with `ResNet101`. The performance with `ResNet101` is similar to that with `ResNet50`. If you want to test the performance with `ResNet101`, you can train your own deetector with [config](https://github.com/open-mmlab/mmtracking/blob/master/configs/det/faster-rcnn_r101_fpn_4e_mot17-half.py)

**Comment by ssyou** [comment]
Ok, Thanks!
