### ISSUE TITLE
Track multiple obejcts on SOT

### ISSUE THREAD

**Issue by callzhang** [open-mmlab/mmtracking#194]
**Checklist**

- [x] I have searched related issues but cannot get the expected help.
- [x] The issue has not been fixed in the latest version.

**Describe the issue**

Can we tracking multiple objects in SOT? As I went through the code, I saw the function description that `gt_bboxes` can have multiple gt bbox. However the implementation doesn't support this.
```
def simple_test(self, img, img_metas, gt_bboxes, **kwargs):
        """Test without augmentation.

        Args:
            img (Tensor): of shape (1, C, H, W) encoding input image.
            img_metas (list[dict]): list of image information dict where each
                dict has: 'img_shape', 'scale_factor', 'flip', and may also
                contain 'filename', 'ori_shape', 'pad_shape', and
                'img_norm_cfg'. For details on the values of these keys see
                `mmtrack/datasets/pipelines/formatting.py:VideoCollect`.
            gt_bboxes (list[Tensor]): list of ground truth bboxes for each
                image with shape (1, 4) in [tl_x, tl_y, br_x, br_y] format.

        Returns:
            dict[str : ndarray]: The tracking results.
        """
```

**Note**
I am trying to implement this as I am trying to build an interactive labeling tool to enable human-in-the-loop annotation. The SOT prediction seems to be better than MOT results in this task.

**Comment by GT9505** [comment]
Yes, you can track multiple objects in SOT. But we not consider to support the feature for now, since it is beyond the scope of SOT task.
You can run SOT demo multi times to achieve this goal, or change the code to support track multiple objects simultaneously in SOT.

**Comment by GT9505** [comment]
Yes, you can modify `simple_test` function in [here](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/models/sot/siamrpn.py#L239) to achieve your goal.
