### ISSUE TITLE
Training on Custom Dataset is stuck at beginning

### ISSUE THREAD

**Issue by rvrsprdx** [open-mmlab/mmtracking#200]
Hi,

thanks for your work!

When I run the train function it seems to load in the config and other necessary information properly.
However, it gets stuck at the point `mmtrack - INFO - workflow: [('train', 1)], max: 4 epochs`.
Nothing happens from here on.
My gpu is at 0% and occupied with 800mb.

Do you know what the issue might be here?

Thank you!

**Comment by ToumaKazusa3** [comment]
Hi~ What command or script did you run? Did you make any modifications on the code or config? What dataset did you use and what task did you run?

**Comment by rvrsprdx** [comment]
It seems to be an issue of the driver/gpu.
I tried it with another gpu+driver combination and the error doesn't appear.
With another codebase I had the same problem. There, I solved it by changing the order of the cv2 and torch import. Maybe this helps someone.
