### ISSUE TITLE
Custom Dataset

### ISSUE THREAD

**Issue by innovator-arjun** [open-mmlab/mmtracking#202]
Hi Team,
In mmtracking, can we use pre-trained weights of selsa -video detection model to train a model using custom data set on top of that?

Another quick question,
1. in selsa the ResNet would be trained from scratch based on the config file right or the backbone would be pretrained?
2. In Imagenet video detection, in the annotations file what is 'generated' means in the .xml

Any guidance would be really great

**Comment by GT9505** [comment]
1. Of course you can.
2. The resnet is pretrained on ImageNet and loaded from torchvison.
3. You can refer to the download section from [this](https://xdshang.github.io/docs/imagenet-vidvrd.html)

**Comment by innovator-arjun** [comment]
Thank you for your reply! really appreciate it

for this question "_can we use pre-trained weights of selsa -video detection model to train a model using custom data set on top of that_" , can you share any reference/documentation to do it using mmtracking?

**Comment by GT9505** [comment]
You can load the pretained weight by setting the value of `load_from` in the [config](https://github.com/open-mmlab/mmtracking/blob/master/docs/tutorials/config_vid.md#an-example-of-dff).

**Comment by meikorol** [comment]
Hi,could you plz give some guidance on VID customizing dataset and training？
