### ISSUE TITLE
Progress of Chinese Documentation

### ISSUE THREAD

**Issue by ToumaKazusa3** [open-mmlab/mmtracking#203]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.
To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] docs/dataset.md
- [x] docs/install.md
- [x] docs/model_zoo.md
- [x] docs/quick_run.md
- [ ] docs/useful_tools_scripts.md
- [ ] docs/change_log.md
- [ ] docs/tutorials/config.md
- [ ] docs/tutorials/config_vid.md
- [ ] docs/tutorials/config_mot.md
- [ ] docs/tutorials/config_sot.md
- [ ] docs/tutorials/customize_dataset.md
- [ ] docs/tutorials/customize_data_pipeline.md
- [ ] docs/tutorials/customize_vid_model.md
- [ ] docs/tutorials/customize_mot_model.md
- [ ] docs/tutorials/customize_sot_model.md
- [ ] docs/tutorials/customize_runtime.md

**Comment by GT9505** [comment]
Since all Chinese Documentation are added in the repo, I unpin and close the issue now.
