### ISSUE TITLE
Bug while training: coco format >"annotations" has no key of "visibility".

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmtracking#206]
Thanks for your error report and we appreciate it a lot.

"e:\mmtracking\mmtrack\datasets\mot_challenge_dataset.py"

**Describe the bug**

 File "e:\mmtracking\mmtrack\datasets\mot_challenge_dataset.py", line 90, in _parse_ann_info
    if (not self.test_mode) and (ann['visibility'] <
KeyError: 'visibility'

**Reproduction**

1. What command or script did you run?

```none
python .\tools\train.py .\TestDetection.py
```

```python
# TestDetection.py
#python tools/train.py TestDetection.py
# The new config inherits a base config to highlight the necessary modification
_base_ = 'configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private-half.py'

# We also need to change the num_classes in head to match the dataset's annotation
model = dict(
    detector=dict(
        rpn_head=dict(bbox_coder=dict(clip_border=False)),
        roi_head=dict(
            bbox_head=dict(bbox_coder=dict(
                clip_border=False), num_classes=1))))

# Modify dataset related settings
dataset_type = 'COCODataset'
classes = ('mouse',)

# # We can use the pre-trained Mask RCNN model to obtain higher performance
data = dict(
    train=dict(
        img_prefix="rats_frames/Mimg",
        classes=classes,
        ann_file='rats_frames/Mimg/Mcoco.json'),
    val=dict(
        img_prefix="rats_frames/Mimg",
        classes=classes,
        ann_file='rats_frames/Mimg/Mcoco.json'),
    test=dict(
        img_prefix="rats_frames/Mimg",
        classes=classes,
        ann_file='rats_frames/Mimg/Mcoco.json'))
```

```json
... Mcoco.json
"images": [
        {
            "height": 852,
            "width": 848,
            "id": 0,
            "file_name": "Mimg00000.png",
            "frame_id": 0,
            "video_id": 1
        },
        {
            "height": 852,
            "width": 848,
            "id": 1,
            "file_name": "Mimg00001.png",
            "frame_id": 1,
            "video_id": 1
        },
...
```

**Environment**

sys.platform: win32
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
GPU 0: GeForce RTX 2080 Ti
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
NVCC: Not Available
GCC: n/a
PyTorch: 1.8.1
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/cb/pytorch_1000000000000/work/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.9.1
OpenCV: 3.4.5
MMCV: 1.3.1
MMCV Compiler: MSVC 192227905
MMCV CUDA Compiler: 10.1
MMTracking: 0.5.0+7c5f87f

**Bug position**
coco format >"annotations" has no key of "visibility".  There was no documentation for "visibility" in custom dataset.

**Comment by OceanPang** [comment]
Did you convert the annotations with this [script](https://github.com/open-mmlab/mmtracking/blob/master/tools/convert_datasets/mot2coco.py)?
