### ISSUE TITLE
“configs/reid/resnet50_b32*8_MOT17.py” 不是windows正确的文件格式

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmtracking#207]
open-mmlab) PS E:\mmtracking> git merge origin/master
error: unable to create file configs/reid/resnet50_b32*8_MOT17.py: Invalid argument

**Comment by OceanPang** [comment]
Which command did you run?

**Comment by OceanPang** [comment]
Try to clone the newest master branch? It seems that you are merging the master branch but have conflicts.

**Comment by chenxinfeng4** [comment]
It's nothing to do with "git-merge", but the WINDOWS don't allow the filename contains char "*".  Can you touch the file "configs/reid/resnet50_b32*8_MOT17.py" in WINDOWS??

**Comment by chenxinfeng4** [comment]
It's nothing to do with "git-merge", but the WINDOWS don't allow the filename contains char "*". Can you touch the file "configs/reid/resnet50_b328_MOT17.py" in WINDOWS??

**Comment by chenxinfeng4** [comment]
It's nothing to do with "git-merge", but the WINDOWS don't allow the filename contains char "\*". I'm wonder how you create the file "configs/reid/resnet50_b32\*8_MOT17.py" in WINDOWS??

**Comment by OceanPang** [comment]
@ToumaKazusa3 Change the filename to `32x8`

**Comment by OceanPang** [comment]
@chenxinfeng4 Currently we all using Linux environment for development and will support more for windows in the future.

**Comment by chenxinfeng4** [comment]
Thank you. Issue close.
