### ISSUE TITLE
Questions on training DeepSort on a custom dataset

### ISSUE THREAD

**Issue by rvrsprdx** [open-mmlab/mmtracking#208]
Hi,

I'm trying to train DeepSort on a custom dataset.
I followed the instructions and converted the data into CocoVID style format and created a config file (I have adapted it from the DeepSort Faster RCNN config).
Now, when running the train I get the error `NotImplementedError: Please train `detector` and `reid` models first and            inference with Tracktor.`
I understand training the detector first.
However, DeepSort uses a deep association metric model. How can I train it?
Also, I don't understand what Tracktor has to do with DeepSort.

I'd appreciate your help. Thank you.

**Comment by OceanPang** [comment]
@ToumaKazusa3 Can you write a document in the folder [reid](https://github.com/open-mmlab/mmtracking/tree/master/configs/reid) to illustrate how to train a reid model?

**Comment by OceanPang** [comment]
The document for training a reid model as been added [here](https://github.com/open-mmlab/mmtracking/blob/master/configs/reid/README.md).
