### ISSUE TITLE
How the SiamRPN SOT can track a non-trained object ?

### ISSUE THREAD

**Issue by doduythao** [open-mmlab/mmtracking#215]
I read the config file and believe that the model trained on LaSOT dataset which doesn't have my object of interest. But when I ran the demo_sot.py, it asked me to bounding box the object I need to track and surprisingly it tracked very well. I don't know why. Anyone know why ?
Thanks

**Comment by GT9505** [comment]
Given an any bounding box in the first frame, the SOT task aims at tracking the object covered by the box in the following frames. Therefore, SOT methods usually need a lot of training data to acquire generalization ability.
