### ISSUE TITLE
demo_mot.py didn't support mot/tracktor

### ISSUE THREAD

**Issue by chenxinfeng4** [open-mmlab/mmtracking#225]
## version
 a8b4152 2021-07-27 (origin/master, origin/HEAD) fix typos in reid config (#222)

## code
python demo/demo_mot.py configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-public-half.py  --input data/MOT17/train/MOT17-02-DPM/img1  --output a.mp4 --fps 2

## output bug
> 2021-07-29 19:34:42,614 - mmtrack - INFO - load detector from: https://download.openmmlab.com/mmtracking/mot/faster_rcnn/faster-rcnn_r50_fpn_4e_mot17-half-64ee2ed4.pth
2021-07-29 19:34:42,615 - mmtrack - INFO - Use load_from_http loader
2021-07-29 19:34:42,808 - mmtrack - INFO - load reid from: https://download.openmmlab.com/mmtracking/mot/reid/reid_r50_6e_mot17-4bf6b63d.pth
2021-07-29 19:34:42,809 - mmtrack - INFO - Use load_from_http loader
[                                                  ] 0/600, elapsed: 0s, ETA:Traceback (most recent call last):
  File "demo/demo_mot.py", line 94, in <module>
    main()
  File "demo/demo_mot.py", line 69, in main
    result = inference_mot(model, img, frame_id=i)
  File "e:\mmtracking\mmtrack\apis\inference.py", line 78, in inference_mot
    data = test_pipeline(data)
  File "D:\L_Anaconda3\envs\open-mmlab\lib\site-packages\mmdet\datasets\pipelines\compose.py", line 40, in __call__
    data = t(data)
  File "e:\mmtracking\mmtrack\datasets\pipelines\loading.py", line 100, in __call__
    detections = results['detections']
KeyError: 'detections'

**Comment by chenxinfeng4** [comment]
**Bug is for `mot/tracktor`**
python demo/demo_mot.py configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-public.py  --input demo/demo.mp4 --output mot2.mp4

**However, OK is for `mot/deepsort`**
python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4

**Comment by chenxinfeng4** [comment]
Ohh, I know the reason. The  `demo/demo_mot.py` should use the "config/***PRIVATE.py" but not the "config/***PUBLIC.py". I strongly suggest you to add this note to your documents. 

Issue closed. Thanks.

**Comment by ToumaKazusa3** [comment]
Thank you for your suggestion. We will add the note to our documents soon. 
The "config/***PUBLIC.py" should use the results of the public detector. If you wanna use the "config/***PUBLIC.py", you can add the public detections in [here](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/apis/inference.py#L75).

**Comment by ToumaKazusa3** [comment]
BTW, we plan to support inference visualization in version 0.7.0, which will be released at the end of August.
