### ISSUE TITLE
RuntimeError: CUDA error

### ISSUE THREAD

**Issue by Richard-mei** [open-mmlab/mmtracking#227]
run demo_mot.py got :  CUDA Error： no kernel image is available for execution on device.

**Comment by ToumaKazusa3** [comment]
Hi~, what command do you run ? What about environment ? BTW, you can use the [error-report](https://github.com/open-mmlab/mmtracking/blob/ecc83b5e6523582b92196095eb21d72d654322f2/.github/ISSUE_TEMPLATE/error-report.md) to create the issue.

**Comment by Richard-mei** [comment]
I just follow the install.md.
Environment_1:
    python: 3.8.10
    pytorch: 1.6.0+cu92
    torchvision: 0.7.0+cu92
    opencv: 4.5.3
    mmcv: 1.3.10
    cuda: 9.2
    mmtracking: 0.6.0+f24cbfc
Command:
    python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
Error:
    CUDA Error： no kernel image is available for execution on device.

**Comment by ToumaKazusa3** [comment]
Please run `python mmtrack/utils/collect_env.py` to collect **entire** environment information. Besides, can you paste the 
**entire** error trackback?

**Comment by Richard-mei** [comment]
Environment:
-------------------------------------
sys.platform: linux
Python: 3.8.10 (default, Jun  4 2021, 15:09:15) [GCC 7.5.0]
CUDA available: True
GPU 0: GeForce GTX TITAN X
CUDA_HOME: /usr/local/cuda-9.2
NVCC: Cuda compilation tools, release 9.2, V9.2.148
GCC: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
PyTorch: 1.6.0+cu92
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 9.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

TorchVision: 0.7.0+cu92
OpenCV: 4.5.3
MMCV: 1.3.10
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 9.2
MMTracking: 0.6.0+f24cbfc
---------------------------------------------------------------------------
run: 
python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
-----------------------------------------------------------------------------
Error:
-----------------------------------------------------------------------------
/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmdet/core/anchor/builder.py:15: UserWarning: ``build_anchor_generator`` would be deprecated soon, please use ``build_prior_generator``
  warnings.warn(
2021-08-06 16:49:55,437 - mmtrack - INFO - load detector from: https://download.openmmlab.com/mmtracking/mot/faster_rcnn/faster-rcnn_r50_fpn_4e_mot17-ffa52ae7.pth
2021-08-06 16:49:55,437 - mmtrack - INFO - Use load_from_http loader
[                                                  ] 0/8, elapsed: 0s, ETA:/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmdet/core/anchor/anchor_generator.py:323: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors``
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmdet/core/anchor/anchor_generator.py:359: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors``
  warnings.warn(
Traceback (most recent call last):
  File "demo/demo_mot.py", line 94, in <module>
    main()
  File "demo/demo_mot.py", line 69, in main
    result = inference_mot(model, img, frame_id=i)
  File "/home/deeplearn/meibp/projects/mmtracking/mmtrack/apis/inference.py", line 92, in inference_mot
    result = model(return_loss=False, rescale=True, **data)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 97, in new_func
    return old_func(*args, **kwargs)
  File "/home/deeplearn/meibp/projects/mmtracking/mmtrack/models/mot/base.py", line 154, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/deeplearn/meibp/projects/mmtracking/mmtrack/models/mot/base.py", line 131, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/deeplearn/meibp/projects/mmtracking/mmtrack/models/mot/deep_sort.py", line 91, in simple_test
    proposals = self.detector.rpn_head.simple_test_rpn(
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmdet/models/dense_heads/dense_test_mixins.py", line 124, in simple_test_rpn
    proposal_list = self.get_bboxes(*rpn_outs, img_metas)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 185, in new_func
    return old_func(*args, **kwargs)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmdet/models/dense_heads/rpn_head.py", line 128, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmdet/models/dense_heads/rpn_head.py", line 220, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmcv/utils/misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/deeplearn/meibp/miniconda3/envs/mtorch1.6/lib/python3.8/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by Richard-mei** [comment]
I am using SSH to connect to my server.

**Comment by ToumaKazusa3** [comment]
You may need to set TORCH_CUDA_ARCH_LIST to reinstall MMCV. The GPU arch table could be found [here](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#gpu-feature-list), i.e. run TORCH_CUDA_ARCH_LIST=6.1 pip install mmcv-full to build MMCV

**Comment by Richard-mei** [comment]
I tried it and it didn't work.
- My SSH server has no permission to connect to the pip,So I install the library through aliyun  image.
This is my whole process of creating the environment:
- $conda create -n mtorch1.6 python=3.8
- $conda activate mtorch1.6
- $pip install torch==1.6.0+cu92 torchvision==0.7.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html -i https://mirrors.aliyun.com/pypi/simple
- $pip install cython -i https://mirrors.aliyun.com/pypi/simple
- $pip install mmcv-full -i https://mirrors.aliyun.com/pypi/simple -f https://download.openmmlab.com/mmcv/dist/cu92/torch1.6.0/index.html 
- $pip install mmdet -i https://mirrors.aliyun.com/pypi/simple
- $git clone https://github.com/open-mmlab/mmtracking.git
- $cd mmtracking
- $pip install -r requirements/build.txt -i https://mirrors.aliyun.com/pypi/simple
- $pip install -v -e . -i https://mirrors.aliyun.com/pypi/simple
# run test:
- $python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4
# RuntimeError: CUDA error: no kernel image is available for execution on the device

**Comment by ToumaKazusa3** [comment]
Have you try `TORCH_CUDA_ARCH_LIST=6.1 pip install mmcv-full -i https://mirrors.aliyun.com/pypi/simple -f https://download.openmmlab.com/mmcv/dist/cu92/torch1.6.0/index.html` to build MMCV instead of `pip install mmcv-full -i https://mirrors.aliyun.com/pypi/simple -f https://download.openmmlab.com/mmcv/dist/cu92/torch1.6.0/index.html`

**Comment by Richard-mei** [comment]
Thank you so much! I tested it on my laptop(rtx 3060) and the same error was reported at first,then I tried `TORCH_CUDA_ARCH_LIST=6.1 pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.0/index.html -i https://mirrors.aliyun.com/pypi/simple`,and now it runs correctly!
note that: -f xxx should be placed before -i xxx.
Thank you again for your help.
