### ISSUE TITLE
ReID training 

### ISSUE THREAD

**Issue by yonafalinie** [open-mmlab/mmtracking#239]
Hi,
I manage to prepare the dataset for ReID model training using mot2reid.py
for MOT17. However, when I try to train using ` resnet50_b32x8_MOT17.py`
I encounter this error 

`TypeError: forward_train() missing 1 required positional argument: 'gt_label'`

Fyi, I did not change anything on the code except the dataset path. May I know how to resolve this error? 

Thank you.

**Comment by ToumaKazusa3** [comment]
Hi~what command do you run ? can you paste the entire error trackback?  BTW, you can use the [error-report](https://github.com/open-mmlab/mmtracking/blob/ecc83b5e6523582b92196095eb21d72d654322f2/.github/ISSUE_TEMPLATE/error-report.md) to create the issue.

**Comment by yonafalinie** [comment]
Hi, ok I already submit new issue with the error-report template. Thank you.
