### ISSUE TITLE
Missing example annotation file. (Dead link)

### ISSUE THREAD

**Issue by askarbozcan** [open-mmlab/mmtracking#241]
Hello, I would like to implement custom dataset(s) and to use them with MMTracking, however the example annotation file link seems to be dead.

https://mmtracking.readthedocs.io/en/tests/assets/demo_cocovid_data/ann.json

Can this file please be updated?

**Comment by GT9505** [comment]
You can refer to [here](https://github.com/open-mmlab/mmtracking/blob/master/tests/data/demo_cocovid_data/ann.json).
We will refactor the documentation of MMTracking before this Wednesday in order to improve and proofread the documentation.

**Comment by askarbozcan** [comment]
Thank you for the link
