### ISSUE TITLE
time estimation log export

### ISSUE THREAD

**Issue by Tortoise17** [open-mmlab/mmtracking#242]
I found this library very helpful. Great work. 
I have to ask, 
Is it possible to keep export of the log while the video (time + weight of the tracking object) is running either live camera or playing recorded video? Please guide me if how to export that log using this library.

**Comment by GT9505** [comment]
Do you mean outputting the time and memory cost of model forward to a log file when running demo?

**Comment by Tortoise17** [comment]
Log file when running demo or video or live video (recording log).

**Comment by GT9505** [comment]
Currently, we don't support exporting log of time and memory cost when running demo.
You can use `time.time()` to estimate time cost and refer [here](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/logger/text.py#L54) to calculate memory cost

**Comment by Tortoise17** [comment]
Sorry, you understood wrong. !!
lI mean log export of the tracked weights (which are the weight of the bounding box with the time)

**Comment by GT9505** [comment]
What do you mean by `the weight of the bounding box`. Does it mean the coordinates of the bounding box?

**Comment by Tortoise17** [comment]
While live video tracking, there are bounding boxes around human being or object.  That has some numbers. I want to get the log of time of video and that time the bounding box number.

**Comment by GT9505** [comment]
If the `numbers` means the id of bounding boxes (i.e., the id of tracked objects), you can export it by recording [result](https://github.com/open-mmlab/mmtracking/blob/master/demo/demo_mot.py#L70).
