### ISSUE TITLE
FileNotFoundError:

### ISSUE THREAD

**Issue by EatonL** [open-mmlab/mmtracking#256]
When I use mot17 dataset, I always report the following error：

**File "/home/ymhj/anaconda3/envs/tz/lib/python3.7/site-packages/mmcv/fileio/file_client.py", line 185, in get
    with open(filepath, 'rb') as f:

FileNotFoundError: [Errno 2] No such file or directory: 'data/MOT17/train/MOT17-05-SDP/img1/000018.jpg'**

And the pictures it can't find during each training are always different

what should i do?

**Comment by GT9505** [comment]
The error information reminds you that the image is not exsited.
Did you follow [dataset.md](https://github.com/open-mmlab/mmtracking/blob/master/docs/dataset.md) to prepare datasets?
You may also need to check whether the MOT17 dataset is unzipped correctly.

**Comment by EatonL** [comment]
I seem to have solved this problem now, but there are new problems

**AssertionError: MMDet==2.11.0 is used but incompatible. Please install mmdet>=(2, 14, 0, 0, 0, 0).**

But my mmdetection is the latest

**Comment by EatonL** [comment]
> The error information reminds you that the image is not exsited.
> Did you follow [dataset.md](https://github.com/open-mmlab/mmtracking/blob/master/docs/dataset.md) to prepare datasets?
> You may also need to check whether the MOT17 dataset is unzipped correctly.

i am sure that my picture exists and i follow dataset.md to prepare dataset (use mot2coco.py and mot2reid.py)

and i found when i use one GPU to train,The error has changed

**File "/mmdetection/mmdet/datasets/samplers/group_sampler.py", line 36, in __iter__
    indices = np.concatenate(indices)
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate**

**Comment by GT9505** [comment]
What command do you run ? What about environment ? BTW, you can use the (error-report)[https://github.com/open-mmlab/mmtracking/blob/master/.github/ISSUE_TEMPLATE/error-report.md] to create the issue.

**Comment by EatonL** [comment]
i run this command -> **./tools/dist_train.sh configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py 2 --work-dir XXX**

my enviroment is:

ubuntu 18.04
python 3.7
mmcv-full 1.3.11
mmdet 2.16.0
mmtrack 0.6.0
torchvision 0.9.1 
pytorch 1.8.1 

Strangely, the error command is _**with open(filepath, 'rb') as f**_:, but it says I lack pictures. Shouldn't this command be used to read pictures?

**Comment by GT9505** [comment]
If you want to train a MOT model, you need to train a detector and a reid model firstly.
Please follow [this](https://github.com/open-mmlab/mmtracking/tree/master/configs) to see how to train a MOT model.
