### ISSUE TITLE
MMPycocotools is no longer necessary

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmtracking#259]
As MMDetection has deprecated mmpycocotools and will install pycocotools during its installation, MMTracking does not need to install mmpycocotools and can remove it in its requirements.

Related PR
https://github.com/open-mmlab/mmdetection/pull/4939

**Comment by GT9505** [comment]
We will fix it later.

**Comment by GT9505** [comment]
fixed in #263
