### ISSUE TITLE
How to get log.json when training?

### ISSUE THREAD

**Issue by roowang** [open-mmlab/mmtracking#272]
I have follow the steps on your page and get the output of a .mp4 video. I want to calculate the mAP and notice that you provide the mAP in your log file.  So  I wonder how to get the log.json file when training?

**Comment by GT9505** [comment]
The log and log.json files will be automatically saved during training.

**Comment by roowang** [comment]
Where is the log and log.json files saved?

**Comment by GT9505** [comment]
The model and logs will be saved based on [Line#90 - Line#96](https://github.com/open-mmlab/mmtracking/blob/master/tools/train.py#L90)
If you can check whether you set `--work-dir` when running `tools/train.py`, or whether there is a `work_dir` key in your config file.

**Comment by roowang** [comment]
OK. Thanks!
