### ISSUE TITLE
How to disable reid module in Tractor during testing/demo

### ISSUE THREAD

**Issue by AyeshaNirma** [open-mmlab/mmtracking#293]
HI,

I want to test Tracktor with a detector but without the Reid module, how can I set it to none in the configs ?

**Comment by GT9505** [comment]
You can set `reid=None` both in [tracker](https://github.com/open-mmlab/mmtracking/blob/master/configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private-half.py#L55) and [model](https://github.com/open-mmlab/mmtracking/blob/master/configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private-half.py#L17).
