### ISSUE TITLE
Where to download the dataset ILSVRC det and vid？

### ISSUE THREAD

**Issue by kuiran** [open-mmlab/mmtracking#299]
Can you provide the detail url to download the det and vid datasets, the url provided in dataset.md can only find the cls_loc dataset.

**Comment by WiWi42** [comment]
Same problem, no idea about where to find or how organize the cls_loc dataset into det and vid. Could you please provide more details how they are produced?

**Comment by WiWi42** [comment]
Same problem, I have downloaded the cls_loc dataset from kaggle, but no idea about how to organize it into det and vid. Could you please provide more details on how they are produced?

**Comment by hopeSerendipity** [comment]
In the website that you provide,there is still just cls_loc dataset without vid and def
