### ISSUE TITLE
Masktrackrcnn evaluation

### ISSUE THREAD

**Issue by sunguanxiong** [open-mmlab/mmtracking#309]
Hi there,

How can I get the evaluation result of MasktrackRCNN? 

I successfully run the training process but when I test with option '--eval track', the evaluation result is all zero.

![image](https://user-images.githubusercontent.com/8849996/140426532-d8c89af5-ee6f-4b4b-9a3e-26848afdcc2b.png)

Is there any possible issue?

Thank you

**Comment by GT9505** [comment]
The validation set of YouTube dataset is not released, you need to submit the zip file to the test serve.

Please refer to [this](https://github.com/open-mmlab/mmtracking/tree/master/configs/vis#testing-with-vis-configs) to test with masktrack rcnn.

**Comment by sunguanxiong** [comment]
> The validation set of YouTube dataset is not released, you need to submit the zip file to the test serve.
> 
> Please refer to [this](https://github.com/open-mmlab/mmtracking/tree/master/configs/vis#testing-with-vis-configs) to test with masktrack rcnn.

Thank you. 👍 

Best

Guanxiong

**Comment by hammerAttack** [comment]
Hi,Do you have this problem：
KeyError：“YouTubeVISDataset：'image_id'”

**Comment by xulinxulin** [comment]
Hello, have you tested the submission server? Where should you submit it.

**Comment by sunguanxiong** [comment]
> Hello, have you tested the submission server? Where should you submit it.

You can submit the result on colab evaluation server. Details in the evaluation section of https://youtube-vos.org/dataset/vis/
