### ISSUE TITLE
unrecognized arguments: --checkpoints checkpoints/fgfa_faster_rcnn_r50_dc5_1x_imagenetvid_20201228_022657-f42016f3.pth

### ISSUE THREAD

**Issue by houchangmin333** [open-mmlab/mmtracking#314]
I have installed it in checkpoints/

**Comment by GT9505** [comment]
Please use `--checkpoint` rather than `--checkpoints`

**Comment by houchangmin333** [comment]
> Please use `--checkpoint` rather than `--checkpoints`

thx its work!
