### ISSUE TITLE
"self._repr_" error in coco_video_dataset.py

### ISSUE THREAD

**Issue by Memz99** [open-mmlab/mmtracking#319]
**Describe the bug**
the `self.__repr__` function of `CocoVideoDataset` is pre-dfined in `mmdet/datasets/custom.py`, which pass a int `idx` to `self.get_ann_info`.   
 ```python
def __repr__(self):
# ...
        # count the instance number in each image
        for idx in range(len(self)):
            label = self.get_ann_info(idx)['labels']
            unique, counts = np.unique(label, return_counts=True)
# ...
```  
But in `mmtrack/datasets/coco_video_dataset.py`, `self.get_ann_info` is defined as  
```python
    def get_ann_info(self, img_info):
        img_id = img_info['id']
        ann_ids = self.coco.get_ann_ids(img_ids=[img_id], cat_ids=self.cat_ids)
        ann_info = self.coco.load_anns(ann_ids)
        return self._parse_ann_info(img_info, ann_info)
```
the `img_info` is passed as a dict.

so when `print(dataset)`, it raise 

```none
"TypeError: 'int' object is not subscriptable"
```

**Reproduction**

```python
# build a coco video dataset...
print(dataset)
```

**Comment by GT9505** [comment]
Hi @Memz99 , Thanks for the error report. Would you like to fix the bug?

**Comment by Memz99** [comment]
> Hi @Memz99 , Thanks for the error report. Would you like to fix the bug?

Happy to help. I'll try it later today. @GT9505
