### ISSUE TITLE
How to package the library for offline installation?

### ISSUE THREAD

**Issue by stephenllh** [open-mmlab/mmtracking#341]
I want to use this library for a Kaggle competition which has restricted Internet access. Initially I wanted to use `pip download` and zip all dependent packages. Then I realized we also need to install using the `setup.py`. So, I am stuck. Can someone guide me?

**Comment by JingweiZhang12** [comment]
Assume you have installed all dependent packages offline, I think it will report all dependencies are satisfied after you run `python setup.py develop` and you don't need to redownload related packages from the internet.

**Comment by stephenllh** [comment]
Thanks
