### ISSUE TITLE
Problem met when running MOT demo

### ISSUE THREAD

**Issue by AndrewGuo0930** [open-mmlab/mmtracking#382]
Hi, I met a problem when I run MOT demo. It said that "**IndexError: tensors used as indices must be long, byte or bool tensors /cluster/home/it_stu12/.conda/envs/gjj/lib/python3.7/tempfile.py:798: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpd1jtqm1n'>   _warnings.warn(warn_message, ResourceWarning)**". Here's my error log.

## Error Log
Traceback (most recent call last):
  File "demo/demo_mot.py", line 94, in <module>
    main()
  File "demo/demo_mot.py", line 70, in main
    result = inference_mot(model, img, frame_id=i)
  File "/cluster/home/it_stu12/main/gjj/mmtracking/mmtrack/apis/inference.py", line 81, in inference_mot
    data = collate([data], samples_per_gpu=1)
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 81, in <dictcomp>
    for key in batch[0]
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 77, in collate
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 77, in <listcomp>
    return [collate(samples, samples_per_gpu) for samples in transposed]
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 81, in collate
    for key in batch[0]
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 81, in <dictcomp>
    for key in batch[0]
  File "/cluster/home/it_stu12/main/gjj/mmcv/mmcv/parallel/collate.py", line 80, in <listcomp>
    key: collate([d[key] for d in batch], samples_per_gpu)
IndexError: tensors used as indices must be long, byte or bool tensors
/cluster/home/it_stu12/.conda/envs/gjj/lib/python3.7/tempfile.py:798: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpd1jtqm1n'>
  _warnings.warn(warn_message, ResourceWarning)
## Environment
No CUDA runtime is found, using CUDA_HOME='/cluster/apps/cuda/10.1'
sys.platform: linux
Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
CUDA available: False
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.1.0
MMCV: 1.4.2
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: not available
MMTracking: 0.8.0+603d6fe

## Some Other Problems

- The doc of MMTracking 0.8 says that MMCV version should be **mmcv-full>=1.3.8, <1.4.0**. But when I install mmcv-full 1.3.9, it told me that my "mmcv-full is too old, please install mmcv-fulll >=1.3.16, <=1.5.0". Which one should I believe?
- The Chinese version doc of MMTracking 0.8 gives a demo script `python demo/demo_mot.py configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py --input demo/demo.mp4 --output mot.mp4`. But I didn't find demo_mot.py in folder demo but found demo_mot_vis.py. Maybe the Chinese doc should be updated?

Thank you so much!

**Comment by GT9505** [comment]
Your PyTorch and MMCV are not compiled with CUDA. Please compile them with CUDA.
All version of  `mmcv-full>=1.3.8` could work well.
Yes, would you like create a PR to update the Chinese docs?

**Comment by AndrewGuo0930** [comment]
But when I run `nvcc -V`, it says
````
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
````
And my PyTorch version is 1.6.0, mmcv-full version is 1.4.2. I don't know why my PyTorch and MMCV aren't compiled with CUDA10.1.
\
Additionally, when I run `torch.cuda.is_available()`, it returns `False`. It's so weird and I didn't find the solution.

**Comment by AndrewGuo0930** [comment]
I'm using the Graphics Card my university provided, but when I run `nvidia-smi`, it returns
````
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
````
😭

**Comment by AndrewGuo0930** [comment]
Here's my latest result after running `collect_env.py`, but I still encounter the same problem as is shown in the **Error Log**. 
## Environment
CUDA available: True
GPU 0: GeForce GTX 1080 Ti
CUDA_HOME: /cluster/apps/cuda/10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.243
GCC: gcc (GCC) 5.4.0
PyTorch: 1.6.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.5 Product Build 20190808 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.5.0 (Git Hash e2ac1fac44c5078ca927cb9b90e1b3066a0b2ed0)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF, 

TorchVision: 0.7.0
OpenCV: 4.1.0
MMCV: 1.4.2
MMCV Compiler: GCC 5.4
MMCV CUDA Compiler: not available
MMTracking: 0.8.0+unknown

**Comment by GT9505** [comment]
You use cuda 10.2 to build pytorch, while you only installed cuda 10.1.
Besides you MMCV is not compiled with cuda.

**Comment by AndrewGuo0930** [comment]
Thank you, I've tried to compile mmcv from source and it worked. Now I can run MOT demo. But when I ran `pip install mmcv-full`, it said "ModuleNotFound: mmcv". Does it mean I could only choose to compile mmcv from source?

**Comment by GT9505** [comment]
You need to use `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.6.0/index.html` to install MMCV with cuda10.1 and pytorch 1.6
