### ISSUE TITLE
difference between "category_id/mot_class_id" and "instance_id/mot_instance_id"

### ISSUE THREAD

**Issue by LingyvKong** [open-mmlab/mmtracking#386]
Hi, I'm trying to use a custom dataset for MOT model. The custom dataset is very similar to MOT17, except that it has two categories. 
When I modify `mot2coco.py`, I have two questions, 

1. what the difference between 'category_id' and  'mot_class_id', 
2. what the difference between 'instance_id' and  'mot_instance_id', 

Are they all useful or only the latter， could you help me?

**Comment by GT9505** [comment]
Only `category_id` and `instance_id` are useful. `mot_class_id` and `mot_instance_id` are annotations of MOT chanllenge format.
