### ISSUE TITLE
Is there any coco format mAP result of bytetrack?

### ISSUE THREAD

**Issue by nemonameless** [open-mmlab/mmtracking#396]
Should I use mmdetection YOLOX to eval the mAP by your weights?

**Comment by GT9505** [comment]
You can directly use mmtracking to get the mAP, as shown in [here](https://github.com/open-mmlab/mmtracking/blob/master/configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot17-private-half.py#L160)
