### ISSUE TITLE
Error in demo_vid.py

### ISSUE THREAD

**Issue by Chop1** [open-mmlab/mmtracking#400]
When looking at demo/demo_vid.py I'm confused.

in ```inference_vid``` (https://github.com/open-mmlab/mmtracking/blob/1d32dc3e54d4a4935e4e2d35b36e281e8335b7eb/mmtrack/apis/inference.py#L138), the code does not actually provide the correct support frame for the model ? (for example for MS ROI align). It only duppliquate (I dont really understand why) the current frame at the start and every frame_stride image ?

```python
        num_left_ref_imgs = ref_img_sampler.get('num_left_ref_imgs')
        frame_stride = ref_img_sampler.get('frame_stride')
        if frame_id == 0:
            for i in range(num_left_ref_imgs):
                one_ref_img = dict(
                    img=image.astype(np.float32).copy(),
                    img_info=dict(frame_id=frame_id))
                data.append(one_ref_img)
        elif frame_id % frame_stride == 0:
            one_ref_img = dict(
                img=image.astype(np.float32).copy(),
                img_info=dict(frame_id=frame_id))
            data.append(one_ref_img)
```

**Comment by Chop1** [comment]
looking at https://github.com/open-mmlab/mmtracking/blob/1d32dc3e54d4a4935e4e2d35b36e281e8335b7eb/mmtrack/models/vid/selsa.py#L171

If I understand, when ```frame id == 0```, the extracted features are stored to serve as futur reference.
Then, features of the current frames are also saved when ```frame_id % frame_stride == 0``` to continue to update the saved feature ?

I'm not sure if there is a discard mecanism here. Like do we store new feature until a memory error ?

Also I still dont understand why in inference.py, when frame_id == 0 the ref image is dupplicate many time.

**Comment by GT9505** [comment]
> looking at
> 
> https://github.com/open-mmlab/mmtracking/blob/1d32dc3e54d4a4935e4e2d35b36e281e8335b7eb/mmtrack/models/vid/selsa.py#L171
> 
> If I understand, when `frame id == 0`, the extracted features are stored to serve as futur reference. Then, features of the current frames are also saved when `frame_id % frame_stride == 0` to continue to update the saved feature ?

Yes.
In `demo_vid.py`, all vid methods are inferenced in online mode. Therefore, we duplicate the first frame at the start to initialize the reference frames feature maps, and duplicate every frame_stride frame to update the reference frames feature maps.
