### ISSUE TITLE
Object counting using MMTracking

### ISSUE THREAD

**Issue by RS00001** [open-mmlab/mmtracking#411]
Hi there,

Could you please point me to the MMTracking variable or a python script that'd let me count objects by ID? Also, are we able to draw a line on the screen to count all the objects that go across the line?

**Comment by JingweiZhang12** [comment]
The MOT tracker in our codebase can track all class-known objects, so you can get the ID number meantime.
`Count all the objects that go across the line` is possible.  Further, the performance may be more accurate if using the mask of the object.
