### ISSUE TITLE
How to sample different number of reference image according to the epoch in 'coco_video_dataset.py'?

### ISSUE THREAD

**Issue by dlsrbgg33** [open-mmlab/mmtracking#425]
I am working on Multi-Object Tracking and trying to re-implement several MOT methods into mmtracking fashion.
One of them is 'MOTR' and its main implementation includes 'The initial length of the video clip is 2 and we gradually increase
it to 3,4,5 at 50th,90th 150th epochs'. 

I think I can implement that if I can call the current epoch in 'ref_img_sampling' of 'coco_video_dataset.py'.

Could you give me a hand on how to do this?

Thank you in advance.

**Comment by JingweiZhang12** [comment]
In our codebase, we can get the current epoch only by calling `runner.epoch`.  
Generally speaking, we realize some functions involved 'epoch' through defining hooks, like [YOLOXModeSwitchHook](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/core/hook/yolox_mode_switch_hook.py#L23)

**Comment by Seerkfang** [comment]
I would like to share my understanding with you. The normal usage of 'ref_image_sampling' is to set parameters of 'ref_image_sampler' in the config of dataset. For example, "ref_img_sampler=dict(num_ref_imgs=1, frame_range=[-1, 1], method='uniform')". In this way, when __get_item__ is called, the reloaded "prepare_data" function in coco_video_dataset would sample the ref_images you want. 
Just as JingWeiZhang12 saying, feel free to custom those hooks before/after epoch. Modify the value of ref_image_sampler maybe an option.
