### ISSUE TITLE
SORT and DeepSORT only track pedestrian class?

### ISSUE THREAD

**Issue by sarimmehdi** [open-mmlab/mmtracking#429]
```
model = init_model(os.path.join('mmtracking/configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-private.py'),
                   os.path.join('models/checkpoints/faster-rcnn_r50_fpn_4e_mot17-half-64ee2ed4.pth'),
                   device='cuda:0')
```
When I print model.CLASSES, I only see the pedestrian class. Am I doing something wrong here or is does SORT and DeepSORT only track one class?

**Comment by sarimmehdi** [comment]
I have confirmed this by running the demo script. Will this feature be implemented in the future?

**Comment by sarimmehdi** [comment]
Which model works with multi-object tracking (so tracking more than one class) out of the box? I tried to look into the ByteTrack implementation here but that too seems to only track pedestrians.

**Comment by JingweiZhang12** [comment]
The MOT models we provided can only track pedestrians.
