### ISSUE TITLE
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward

### ISSUE THREAD

**Issue by kokeliang** [open-mmlab/mmtracking#446]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Reproduction**

1. What command or script did you run?

```  
python ./tools/train.py ./configs/vis/masktrack_rcnn/masktrack_rcnn_r50_fpn_12e_youtubevis2021.py  --work-dir ./work_dirs/
```

3. What dataset did you use and what task did you run?

I'm using mask track RCNN to train youtubevis data.

**Error traceback**

```
 ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #2 'target' in call to _thnn_nll_loss_forward
```

Does anyone know how to solve this problem?  Thank you very much.

**Comment by JingweiZhang12** [comment]
You convert the `target`, i.e., `label`, from int to long in the data pipeline.

**Comment by kokeliang** [comment]
@JingweiZhang12 Thank you for your answer. One more question: how can I change the dtype int to dtype long in `SeqLoadAnnotations` of the pipeline? Thank you again.
