### ISSUE TITLE
make youtube_vis dataset

### ISSUE THREAD

**Issue by kokeliang** [open-mmlab/mmtracking#448]
Hello. Because mask track rcnn now only supports **youtube_vis** dataset, so how can we make youtube_vis dataset? Do you have any recommended tools to do it? Thanks a lot.

**Comment by JingweiZhang12** [comment]
What does this word `make youtube_vis dataset` mean？

**Comment by kokeliang** [comment]
I want to make my own dataset like youtube_vis for mask track rcnn.

**Comment by JingweiZhang12** [comment]
[labelbee](https://github.com/open-mmlab/labelbee-client) may be a good choice.

**Comment by kokeliang** [comment]
@JingweiZhang12 Thank you for your suggestion. But labelbee can't do video tracking and segmentation labeling. Do you know the other tools that can do it?
