### ISSUE TITLE
Some TypeError occured when I use YOLOX with MOT17 Dataset

### ISSUE THREAD

**Issue by HillbertChan** [open-mmlab/mmtracking#454]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
I try to use YOLOX's config in mmdetection to train a tracker with MOT17 Dataset. But TypeErro Occured many times. Firstly, the 'results'(which conclude 2 dicts but 1 in your code ) occured :
**TypeError: list indices must be integers or slices, not str**
I worked out it after I found the different count of dicts.
But when I continue run the code, the new err occured:

Original Traceback (most recent call last):
  File "D:\Python3810\lib\site-packages\torch\utils\data\_utils\worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "D:\Python3810\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Python3810\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Python3810\lib\site-packages\mmdet\datasets\dataset_wrappers.py", line 409, in __getitem__
    indexes = transform.get_indexes(self.dataset)
  File "D:\Python3810\lib\site-packages\mmdet\datasets\pipelines\transforms.py", line 2320, in get_indexes
    gt_bboxes_i = dataset.get_ann_info(index)['bboxes']
  File "D:\Python3810\lib\site-packages\mmdet\datasets\coco_video_dataset.py", line 234, in get_ann_info
    img_id = img_info['id']
**TypeError: 'int' object is not subscriptable**

I try to debug it, however, little progress (maybe I am a new coder LOL)

**Reproduction**

1. What command or script did you run?

python tools/train.py configs/det/my_yolox.py

this is my command, my_yolo.py is same as the base YOLOX but changed dataset to motchallenge

**Environment**

PY ==3.8.10
Torch == 1.10.0+cu113

Thanks a lot sincerely for you!!!!

**Comment by JingweiZhang12** [comment]
Weird!  Why your `coco_video_dataset` class is in `mmdet` rather than `mmtrack`?
Could you share your `configs/det/my_yolox.py`?

**Comment by HillbertChan** [comment]
Actually, I want to try MOT17 in mmdet and copy the related dataset py files to mmdet, but occured the same TypeError.

part of my `my_yolox.py` is 
USE_MMDET = True
_base_ = ['../_base_/models/yolox_x_8x8.py',
          '../_base_/datasets/mot_challenge_det.py', '../_base_/default_runtime.py']

img_scale = (640, 640)

# model settings
model = dict(
    type='YOLOX',
    input_size=img_scale,
    random_size_range=(15, 25),
    random_size_interval=10,
    backbone=dict(type='CSPDarknet', deepen_factor=0.33, widen_factor=0.5),
    neck=dict(
        type='YOLOXPAFPN',
        in_channels=[128, 256, 512],
        out_channels=128,
        num_csp_blocks=1),
    bbox_head=dict(
        type='YOLOXHead', num_classes=80, in_channels=128, feat_channels=128),
    train_cfg=dict(assigner=dict(type='SimOTAAssigner', center_radius=2.5)),
    test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.65)))

# dataset settings
data_root = 'data/mot/MOT17/'
dataset_type = 'MOTChallengeDataset'
...

the other part is same as` yolox_s_8x8_300e_coco.py`

**Comment by JingweiZhang12** [comment]
The error may be caused by your refactor of the related datasets.
You can check the content of  `self.data_infos`  in the `coco_video_dataset`. Normally, it's of type `list[dict]`， and each `dict` in it contains the information of each image in the training stage.

**Comment by HillbertChan** [comment]
I checked all the 7992 `dict` in `self.data_infos`, and all of them seems no problem. I rebuged again and found the key of this Error is   `img_id = img_info['id']`, which in `coco_video_dataset.py` , the func `get_ann_info`, as shown in my first comment. 
The img_info should be a dict, but after the func __getitem__ in Class MultiImageMixDataset, it would be a int ! 
That's Weird and I am going to find the reason.
Thanks for you attention, and I will close this issue after I fix this problem~

**Comment by HillbertChan** [comment]
I checked all the 7992 `dict` in` self.data_infos`, and all of them seems no problem. I rebuged again and found the key of this Error is `img_id = img_info['id']`, which in `coco_video_dataset.py` , the func `get_ann_info`, as shown in my first comment.
The` img_info` should be a `dict`, but after the func` __getitem__ `in Class `MultiImageMixDataset`, it would change to an `int `!
That's Weird and I am going to find the reason.
Thanks for you attention, and I will close this issue after I fix this problem~

**Comment by HillbertChan** [comment]
Finally, runing successfully since I restart everthing. The problem seems was caused by me since I tried to put MOT Challenge Datasets into mmdet and changed your source code to suit the datasets. That is not a  wise choice.
Thanks for your help sincerely again~
