### ISSUE TITLE
VID dataset preparation

### ISSUE THREAD

**Issue by AllieLan** [open-mmlab/mmtracking#468]
I want to use my own VID dataset to train a model, and my own datasets have transferred videos to frames, and the format of  frames' annotation is VOC format.
![image](https://user-images.githubusercontent.com/94182491/159843877-cbeb4627-5707-4d74-9dab-e53323936118.png)
![image](https://user-images.githubusercontent.com/94182491/159843043-244a2383-aa02-4020-8853-83151388f8ce.png)
Accourding to the dataset preparation.md, I put the frames and the .xml into Data and Annotations, respectively. 
There is a reminder:  
![image](https://user-images.githubusercontent.com/94182491/159841456-6d19e519-83ac-42f3-881b-d18aa7b919fe.png)
I am confused about the **Lists**, and how to generate the txt?
![image](https://user-images.githubusercontent.com/94182491/159841755-b0f23b1f-96e7-446b-ada6-b3c1ef3ed00d.png)
What is the meaning of **the last three number** in the **VID_train_15frames.txt**?  and the  **the last three number** in the **VID_val_videos.txt**
![image](https://user-images.githubusercontent.com/94182491/159841898-09997a7c-c528-4ef5-a39f-29cdd2d63b14.png)
![image](https://user-images.githubusercontent.com/94182491/159842415-34f14657-a3cb-457b-acdf-8252854e05f8.png)
I wonder whether the VID_val_videos.txt is necessary becasuse I don't put the videos into the data.
Thank you

**Comment by hutIngk** [comment]
> I want to use my own VID dataset to train a model, and my own datasets have transferred videos to frames, and the format of frames' annotation is VOC format. ![image](https://user-images.githubusercontent.com/94182491/159843877-cbeb4627-5707-4d74-9dab-e53323936118.png) ![image](https://user-images.githubusercontent.com/94182491/159843043-244a2383-aa02-4020-8853-83151388f8ce.png) Accourding to the dataset preparation.md, I put the frames and the .xml into Data and Annotations, respectively. There is a reminder: ![image](https://user-images.githubusercontent.com/94182491/159841456-6d19e519-83ac-42f3-881b-d18aa7b919fe.png) I am confused about the **Lists**, and how to generate the txt? ![image](https://user-images.githubusercontent.com/94182491/159841755-b0f23b1f-96e7-446b-ada6-b3c1ef3ed00d.png) What is the meaning of **the last three number** in the **VID_train_15frames.txt**? and the **the last three number** in the **VID_val_videos.txt** ![image](https://user-images.githubusercontent.com/94182491/159841898-09997a7c-c528-4ef5-a39f-29cdd2d63b14.png) ![image](https://user-images.githubusercontent.com/94182491/159842415-34f14657-a3cb-457b-acdf-8252854e05f8.png) I wonder whether the VID_val_videos.txt is necessary becasuse I don't put the videos into the data. Thank you

i have met save problem，so could u tell me how to prepare the dataset and what the correct dataset looks like？
