### ISSUE TITLE
I want to train the MaskTrack R-CNN in my own dataset

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmtracking#481]
Hello! I want to train the MaskTrack R-CNN in my own dataset, which format of dataset i can use?

**Comment by JingweiZhang12** [comment]
Please refer to  https://github.com/open-mmlab/mmtracking/blob/master/docs/en/tutorials/customize_dataset.md

**Comment by lijoe123** [comment]
Thank you! But i still don't understand how to get the dataset of Youtubevis format(就是用什么软件去制作youtubevis 类型的数据集).

**Comment by JingweiZhang12** [comment]
Maybe you can consult the official team of Youtubevis.
