### ISSUE TITLE
TypeError: DeepSORT: __init__() got an unexpected keyword argument 'backbone'

### ISSUE THREAD

**Issue by castrovictor** [open-mmlab/mmtracking#485]
**Describe the bug**

I am trying to train a tracker with Retina as detector, using the MOT dataset. I have followed the tutorials and tried to understand the configs, but I can't still make it work. I compare with what is done in the examples and the configs provided, but still does not work. When I try to train, I get the following error:
`TypeError: DeepSORT: __init__() got an unexpected keyword argument 'backbone'`

**Reproduction**

1. What command or script did you run?

```bash
python tools/train.py /home/ubuntu/mmtracking/configs/mot/deepsort/sort_retinanet_r50_fpn_4e_mot17-private.py

```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
Yes, I understand what I have modified. here I share the configs:
/home/ubuntu/mmtracking/configs/mot/deepsort/sort_retinanet_r50_fpn_4e_mot17-private-half.py -> [https://codeshare.io/6pJoqg](https://codeshare.io/6pJoqg)
/home/ubuntu/mmtracking/configs/mot/deepsort/sort_retinanet_r50_fpn_4e_mot17-private.py -> [https://codeshare.io/mpDXe1](https://codeshare.io/mpDXe1)
Detection model, works ok in MMDetector: [configs/models/retina_r50_mod.py](https://codeshare.io/Ad8Wye)

latest.pth is the checkpoint/trained model generated with MMDetector and the config of retina_50 given above.

3. What dataset did you use and what task did you run?
 MOT

**Environment**
Environment exactly as in the installation guide.

**Error traceback**
If applicable, paste the error trackback here.

```none
2022-04-07 12:42:58,405 - mmtrack - INFO - Set random seed to 484183397, deterministic: False
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'backbone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 210, in <module>
    main()
  File "tools/train.py", line 182, in main
    model = build_model(cfg.model)
  File "/home/ubuntu/mmtracking/mmtrack/models/builder.py", line 35, in build_model
    return MODELS.build(cfg)
  File "/home/ubuntu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/home/ubuntu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/home/ubuntu/anaconda3/envs/openmmlab/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: DeepSORT: __init__() got an unexpected keyword argument 'backbone'

```

**Comment by JingweiZhang12** [comment]
Hi, different from the model configs in `mmdetection`,  the detector model in `mmtracking` needs to be wrapped into a dict like:  dict(detector=dict('type='RetinaNet', backbone=...)). 
You can refer to this: 
https://github.com/open-mmlab/mmtracking/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py#L2

**Comment by castrovictor** [comment]
> Hi, different from the model configs in `mmdetection`, the detector model in `mmtracking` needs to be wrapped into a dict like: dict(detector=dict('type='RetinaNet', backbone=...)). You can refer to this: https://github.com/open-mmlab/mmtracking/blob/master/configs/_base_/models/faster_rcnn_r50_fpn.py#L2

Hi. Thank you for your response. I read the configs but I didn't notice that detail. Now I do not get that error (I solved another one I got). Not it should work, but I get `NotImplementedError: Please train `detector` and `reid` models firstly, then                 inference with SORT/DeepSORT.`

I provided the checkpoint produced by the mmdetector. What am I missing?

**Comment by Seerkfang** [comment]
Yes, you only need to train the detector and ReID model.

**Comment by castrovictor** [comment]
> Yes, you only need to train the detector and ReID model.

Thanks for the quick response! Dealing with [this](https://github.com/open-mmlab/mmtracking/issues/132) now, it seems the dependencies have some problems/bugs (at least in my machine)
