### ISSUE TITLE
MMTracking for training with images to use for videos? And use a pretrained yolov4 model ?

### ISSUE THREAD

**Issue by whiteplatin** [open-mmlab/mmtracking#489]
Hello, 

The answers to my questions may be self evident if you come from PyTorch, but sadly incomplete or outdated info for real custom datasets in the otherwise great docs.

Two quick questions: 
**1.** Can I only use images to train a model to use for video tracking, or are videos required ? (Google Coco-VID format, youll get zero results.)

**2.** I already have a trained YOLOv4 model and its weights file, can I convert the .weights file into a .pth file and run some inferencing then ?

Thanks.

**Comment by JingweiZhang12** [comment]
1. Yes, you can use images to train a model. Please refer to [this](https://github.com/open-mmlab/mmtracking/blob/master/configs/_base_/datasets/imagenet_vid_dff_style.py#L49)
2. Yes, but you should make sure to use the right model configs in `mmdet`.

**Comment by whiteplatin** [comment]
[This](https://github.com/open-mmlab/mmtracking/blob/master/configs/_base_/datasets/imagenet_vid_dff_style.py#L49) is also using a video dataset. 
I just want to train images for object detection that can later be used with mmtracking.
My dataset structure:

```
data/
│
└───project1/    
│         │  
│         └───images/ (random non ordered images)
│         │          │  1.jpg
│         │          │  2.jpg
│         │          │   ...
│         │   
│         └───annotations/
│                      │   train.json
│                      │   valid.json
```

Is there already a ready to use config, or what would be the fastest way to do so ?
