### ISSUE TITLE
How to sequentially process the data with more pipelines?

### ISSUE THREAD

**Issue by zengwz** [open-mmlab/mmtracking#550]
I want to use mosaic belong to mmdetection to sequentially process the data as shown in the tutorials. some pipelines, such as Pad and LoadImageFromFile have achieved in the mmtracking. 
![image](https://user-images.githubusercontent.com/57857883/167247492-7c89e1c4-9a2a-467f-80a5-c12fc3d567fc.png)

When I try to follow the tutorials to achieve SeqMosaic, it is wrong.
![image](https://user-images.githubusercontent.com/57857883/167247599-3ddf7676-e8e0-49f8-9ce9-dd936dbf621d.png)

![image](https://user-images.githubusercontent.com/57857883/167247554-c1c54eb6-a6b1-4326-8f48-f9009c6d0234.png)

**Comment by dyhBUPT** [comment]
To make it easier to understand, we recommend using the [Issue Template](https://github.com/open-mmlab/mmtracking/tree/master/.github/ISSUE_TEMPLATE) to describe your problem.
