### ISSUE TITLE
Which annotation tool do you recommend for custom dataset? Thank you a lot!

### ISSUE THREAD

**Issue by newforrestgump001** [open-mmlab/mmtracking#565]
Which annotation tool do you recommend for VID (video object detection) custom dataset? Thank you a lot!

**Comment by dyhBUPT** [comment]
Hi, it depends on your preference.
For example, [labelme](https://github.com/wkentaro/labelme) is ok, which is one of the most popular annotation tools.

Best wishes.

**Comment by newforrestgump001** [comment]
I got it, Thank you a lot!

**Comment by meikorol** [comment]
Hi,could you plz give some guidance on VID customizing dataset and training？
