### ISSUE TITLE
Someting seems wrong when test Siamrpn++ on lasot

### ISSUE THREAD

**Issue by kuiran** [open-mmlab/mmtracking#566]
![image](https://user-images.githubusercontent.com/25083462/169693200-3479b854-c8d0-48c9-8d00-fdc3cbf0629a.png)

**Comment by kuiran** [comment]
There seems too many frames than the dataset have

**Comment by kuiran** [comment]
I test on single gpu，it is right，I think something wrong with multigputest

**Comment by dyhBUPT** [comment]
Hi, it is just a bug of display while multi-GPU testing.
You can ignore the problem and perform multi-GPU testing normally.

Best wishes.
