### ISSUE TITLE
Backdrops in QDTrack

### ISSUE THREAD

**Issue by Leo63963** [open-mmlab/mmtracking#568]
Hi! Really admire your great work, thanks for your sharing.
I am quite confused about backdrops.
The thing is, the backdrops are those unmatched detections, which are kept for one frame for potential matching. The embeddings and bboxes of backdrops are stored at self.backdrops, and _"cat"_ with self.tracklets at self.memo. Therefore, the backdrops are regarded as one of tracklets to match with detections in the next frame, i.e., data association.

However, if matched by bi-softmax with a higher score, it still can not be matched successfully since the **id** of backdrops are all set to **-1**, which is violate the following code:
https://github.com/open-mmlab/mmtracking/blob/c250394b8a9ca95dae2ad49efe2d92ae450f605a/mmtrack/models/trackers/quasi_dense_embed_tracker.py#L255
Thus, the matching between backdrops and detections is unavailable. 
Is that true? Thanks.

**Comment by Seerkfang** [comment]
Backdrops are used to satisfy one-to-one correspondence. They prevent detection results associated with wrong tracklets, though with high similarity scores.

**Comment by Leo63963** [comment]
Thanks for your reply.
