### ISSUE TITLE
When will mmtracking support mmcv>=1.4.0?

### ISSUE THREAD

**Issue by pallgeuer** [open-mmlab/mmtracking#569]
I am a user of MMPose, which has MMTracking as a dependency. This is a problem for me because MMTracking requires:
```
mmcv-full>=1.3.8,<1.4.0
```
and thus limits the version of MMClassification to maximum 0.19.0 (as beyond that MMClassification requires `mmcv>=1.4.2` or higher). I however want to use MMPose in combination with the latest MMClassification (0.23.0).

Development of MMCV in the mean time is >1.5, so it really feels like MMTracking is just stuck far in the past. When will this be fixed?

**Comment by pallgeuer** [comment]
Good to know!
Then I would recommend updating the project requirements file with this information (I believe the mim tool reads this information and makes decisions based on that):
https://github.com/open-mmlab/mmtracking/blob/master/requirements/mminstall.txt
This is mminstall.txt from the latest master branch and at time of writing for 0.13.0 has:
```
mmcls>=0.14.0
mmcv-full>=1.3.8,<1.4.0
mmdet>=2.14.0,<3.0.0
```

**Comment by JingweiZhang12** [comment]
Sorry, I didn't update the `mminstall.txt` timely. We will appreciate it if you can fix this bug about docs.

**Comment by JingweiZhang12** [comment]
We try to fix it: https://github.com/open-mmlab/mmtracking/pull/572

**Comment by pallgeuer** [comment]
Closing because it seems #572 is merged now.
