### ISSUE TITLE
IndexError: CocoVideoDataset: list assignment index out of range

### ISSUE THREAD

**Issue by godwinrayanc** [open-mmlab/mmtracking#573]
**Describe the issue**

**Reproduction**

1. What command or script did you run?

```none
python tools/train.py configs/selsa_faster_rcnn_r50_dc5_1x_CocoVideoDataset.py
```

2. What config dir you run?
I wish to use SELSA for my custom dataset
```none
_base_= [
    './_base_/models/faster_rcnn_r50_dc5.py',
    './_base_/default_runtime.py'
]


#model settings
model = dict(
    type='SELSA',
    detector=dict(
        roi_head=dict(
            type='SelsaRoIHead',
            bbox_head=dict(
                num_classes=10,
                type='SelsaBBoxHead',
                num_shared_fcs=2,
                aggregator=dict(
                    type='SelsaAggregator',
                    in_channels=1024,
                    num_attention_blocks=16)))))

 

# dataset settings
dataset_type = 'CocoVideoDataset'
classes = ('0','1','2','3','4','5','6','7','8','9')


img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)

train_pipeline = [

    
    # First pipeline to load multi images from files path
    dict(type='LoadMultiImagesFromFile'), 
    
    # Second pipeline to load annotations for multi images
    # Whether to use bounding box, True for detection
    # Whether to use instance ids, True for detection
    dict(type='SeqLoadAnnotations', with_bbox=True, with_track=True), 

    # Augmentation pipeline that resize the multi images and their annotations
     # Augmentation pipeline that resize the multi images and their annotations
    dict(type='SeqResize', img_scale=(600, 600), keep_ratio=True),

    #dict(type='SeqRandomFlip', share_params=True, flip_ratio=0.5),

    dict(type='SeqNormalize', **img_norm_cfg),
    dict(type='SeqPad', size_divisor=16),
    dict(
        type='VideoCollect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_instance_ids']),
    dict(type='ConcatVideoReferences'),
    dict(type='SeqDefaultFormatBundle', ref_prefix='ref')
]

data = dict(
    samples_per_gpu=1,
    workers_per_gpu=2,
    train=dict(
            type=dataset_type,
            ann_file='/home/rayan/mmtracking/data/mmd_mnist/annotations/train_mmd.json',
            classes=classes,

            ref_img_sampler=dict(
                num_ref_imgs=2,
                frame_range=9,
                filter_key_img=True,
                method='bilateral_uniform'),
            pipeline=train_pipeline)
        )

# optimizer
optimizer = dict(type='SGD', lr=0.01, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(
    _delete_=True, grad_clip=dict(max_norm=35, norm_type=2))

# learning policy
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=1.0 / 3,
    step=[2, 5])

# runtime settings
total_epochs = 7 # Total epochs to train the model
evaluation = dict(metric=['bbox'], interval=7) # The config to build the evaluation hook
work_dir = '../mmtrack_output/tmp'

```

3. Did you make any modifications to the code or config? Did you understand what you have modified?
Yes, I changed the num_classes in the 'faster_rcnn_r50_dc5.py' to 10 and made sue bbox_head also has 10 classes.
5. What dataset did you use?
I use a custom dataset based on MNIST with annotations created as per the ann.json example. Here is a snippet of it. It has 120 videos with different lengths.
```
{
 "categories": [
        {
            "id": 1,
            "name": 0
        },
        {
            "id": 2,
            "name": 1
        }

"videos": [
        {
            "id": 1,
            "name": "dia_xy_0"
        },
        {
            "id": 2,
            "name": "dia_xy_1"
        }
],
    "images": [
        {
            "file_name": "/home/rayan/mmtracking/data/mmd_mnist/train/twbb_0_00000.jpg",
            "height": 150,
            "width": 150,
            "id": 1,
            "video_id": 1,
            "frame_id": 0
        },
.
.
.
{
            "file_name": "/home/rayan/mmtracking/data/mmd_mnist/train/twbb_0_00045.jpg",
            "height": 150,
            "width": 150,
            "id": 46,
            "video_id": 1,
            "frame_id": 45
        },
        {
            "file_name": "/home/rayan/mmtracking/data/mmd_mnist/train/twbb_1_00046.jpg",
            "height": 150,
            "width": 150,
            "id": 47,
            "video_id": 2,
            "frame_id": 46
        }
],
    "annotations": [
        {
            "id": 1,
            "image_id": 1,
            "video_id": 1,
            "category_id": 1,
            "bbox": [
                0,
                0,
                30,
                30
            ],
            "area": 900,
            "occluded": false,
            "truncated": false,
            "iscrowd": false,
            "ignore": false,
            "is_vid_train_frame": true,
            "visibility": 1.0
        },
{
            "id": 46,
            "image_id": 46,
            "video_id": 1,
            "category_id": 1,
            "bbox": [
                45,
                45,
                30,
                30
            ],
            "area": 900,
            "occluded": false,
            "truncated": false,
            "iscrowd": false,
            "ignore": false,
            "is_vid_train_frame": true,
            "visibility": 1.0
        },
        {
            "id": 47,
            "image_id": 47,
            "video_id": 2,
            "category_id": 2,
            "bbox": [
                0,
                0,
                30,
                30
            ],
            "area": 900,
            "occluded": false,
            "truncated": false,
            "iscrowd": false,
            "ignore": false,
            "is_vid_train_frame": true,
            "visibility": 1.0
        }
]
}
```
**Environment**

1. Please run `python mmtrack/utils/collect_env.py` to collect necessary environment information and paste it here.
sys.platform: linux
Python: 3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA GeForce GTX 1050 Ti
CUDA_HOME: None
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.11.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.11.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.12.0
OpenCV: 4.5.5
MMCV: 1.5.0
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.2
MMTracking: 0.13.0+8e15b9b

2. You may add addition that may be helpful for locating the problem, such as
   1. Problems occur at the coco_video_parser.py file at line [124](https://github.com/open-mmlab/mmtracking/blob/2542848f4b441e92b5b7c54c32285d0e675dac1a/mmtrack/datasets/parsers/coco_video_parser.py#L124) 
   2. I have the first video with id = (1-46) and frame_id = (0-45) , However the loop proceeds to 47 (second video) and gives me an list assignment index out of range.
 

**Results**

![image](https://user-images.githubusercontent.com/74194500/170559271-74553f27-f241-4e40-a9c8-6fa0a1310d72.png)

**Issue fix**

**Comment by pixeli99** [comment]
Hi, [godwinrayanc](https://github.com/godwinrayanc),

Personally, I think there is a problem with your dataset annotation , but I'm sorry I can't give you an accurate problem location. I suggest you debug it.

`get_img_ids_from_vid`  retrieves the IDs of all images corresponding to the current video.
I noticed that you said that the function accessed the `47` index in the loop, so I think it is possible that your `video_id` is not handled correctly, and there is something wrong with the annotation file.

You should focus on whether the `self.vidToImgs[vidId]` stores the correct results.
https://github.com/open-mmlab/mmtracking/blob/2542848f4b441e92b5b7c54c32285d0e675dac1a/mmtrack/datasets/parsers/coco_video_parser.py#L121

**Comment by godwinrayanc** [comment]
Hello, @pixeli99 
Thanks for reply. 
I check the vidId and its shows it takes two videos (1&2). Is it supposed to take two videos or only one video?
Is there a sample annotation file that has more than one video in the repository?

**Comment by lijoe123** [comment]
Hello @godwinrayanc , I had get trouble in how to make my own CocoVideoDataset. Could you please tell me how to make the CocoVideoDataset?
