### ISSUE TITLE
Create config to run demo_mot_vis.py with custom bounding boxes.

### ISSUE THREAD

**Issue by NikoRohr** [open-mmlab/mmtracking#581]
Hello,

Im trying to run demo_mot_vis.py on a video of the MOT17_tiny dataset. Here is what I have done so fare:

1) Download and convert dataset as in the tutorial.
2) Extract the detections of one video (train/MOT17-02-FRCNN) and saved it as pkl file in the format dict(det_bboxes=dict(img1_name: [], img2_name: [], ...)). I also removed the path to the images so they look like "000001.jpg"
3) I use this config file as base: '/configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-public.py' I modified it as follows:
```
mot_config = mmcv.Config.fromfile(ROOT + '/configs/mot/deepsort/sort_faster-rcnn_fpn_4e_mot17-public.py') #ROOT is the path to mmtracking
mot_config.data_root = DATASET #DATASET is the path to MOT17_tiny
mot_config.data.train.detection_file = DATASET + 'annotations/det_MOT17-02-FRCNN.pkl' #det_MOT17-02-FRCNN.pkl is my modified pickle file
mot_config.data.test.detection_file = DATASET + 'annotations/det_MOT17-02-FRCNN.pkl'
mot_config.data.val.detection_file = DATASET + 'annotations/det_MOT17-02-FRCNN.pkl'
```
4) Then I tried to run the script via 
```
!python $ROOT/demo/demo_mot_vis.py $config --input $imgs_path --output mot_demo.mp4 --fps 25
# config is where I saved the modified configurations
```

Finally I get the Error: 
```
 File "../mmtracking/demo/demo_mot_vis.py", line 103, in <module>
    main()
  File "../mmtracking/demo/demo_mot_vis.py", line 78, in main
    result = inference_mot(model, img, frame_id=i)
  File "../mmtracking/mmtrack/apis/inference.py", line 108, in inference_mot
    data = test_pipeline(data)
  File "../env_mmtracking/lib/python3.8/site-packages/mmdet/datasets/pipelines/compose.py", line 41, in __call__
    data = t(data)
  File "../mmtracking/mmtrack/datasets/pipelines/loading.py", line 101, in __call__
    outs_det = results2outs(bbox_results=results['detections'])
KeyError: 'detections'
```
I'm afraid I'm missing something basic about loading the detections and would appreciate some help.

**Comment by dyhBUPT** [comment]
Same problem with #580. 
You are suggested to use `tools/test.py` instead of `demo_mot_vis.py` when you are using the "public config".
Please let me know if this helps.

Best wishes.

**Comment by NikoRohr** [comment]
Thank you very much, now it works. But I am not sure whether it uses the detections I gave SORT or not. Is there any possibility to validate that SORT uses the provided bboxes?

**Comment by dyhBUPT** [comment]
The simplest way, maybe, is to delete most of the detections in your .pkl file and see if the tracking results are consistent with it. :D

**Comment by NikoRohr** [comment]
Okay, good idea. Thank you:D
