### ISSUE TITLE
Is ILSVRC2017 VID dataset adaptive for the ''Lists'' in ''dataset.md''?

### ISSUE THREAD

**Issue by Ares-debugger** [open-mmlab/mmtracking#601]
We use ILSVRC2017 VID dataset and try to train the DFF model.  We also download four files in the ''ImageSet'' of FGFA project according to ''dataset.md''. However, the files record the dataset with ''2015'' in all the paths, e.g., ''/train/ILSVRC20150000/...''. Error report when using the ''tools/convert_datasets/ilsvrc/imagenet2coco_vid.py'':  [Errno 2] No such file or directory: './data/ILSVRC/Annotations/VID/train/ILSVRC2015_VID_train_0000/ILSVRC2015_train_00000000/000000.xml'.

we uploaded the screenshot of data directory structure in project and error message.  Can we just change the ''2015'' to ''2017'', or use the files in ''ImageSets'' of ILSVRC2017 dataset to make a new tool? Thank you very much for answering.

**Comment by JingweiZhang12** [comment]
You had better check whether the file structure and annotation format of ILSVRC2015 and ILSVRC2017 are the same. We have not used `tools/convert_datasets/ilsvrc/imagenet2coco_vid.py` on ILSVRC2017.

**Comment by Ares-debugger** [comment]
Thank you. We download the ILSVRC2015 dataset and start training. But it make us curious that why DET dataset is also needed in VID task (the json generated by DET dataset is used for VID training and we know that the pictures in DET dataset are discrete)? Can we only use the VID dataset? If the DET dataset must be used, how can we organize the data structure on other VID dataset (such as UAVDT)?

**Comment by JingweiZhang12** [comment]
It is a convention in VID field that the DET dataset is used in VID task. You can also don't use it, but the performance may drop. 
If you add other datasets in VID tasks, you can refer to https://github.com/open-mmlab/mmtracking/blob/master/docs/en/tutorials/customize_dataset.md

**Comment by Ares-debugger** [comment]
Got it, thank you.
