### ISSUE TITLE
Question about QDtrack TAO

### ISSUE THREAD

**Issue by trofik00777** [open-mmlab/mmtracking#607]
Hello! I can not fully understand the `QDtrack` model, which is trained on the `TAO` dataset. Can I choose which specific objects I want to detect (since all objects are detected by default) ?

**Comment by pixeli99** [comment]
Hi,

You can choose the category you need, the current `qdtrack` also selected 482 categories.

But there are bugs in the training of qdtrack on TAO. I will fix them as soon as possible.

**Comment by pixeli99** [comment]
I will paste the PR link here if I fix it.

**Comment by pixeli99** [comment]
https://github.com/open-mmlab/mmtracking/pull/609

**Comment by trofik00777** [comment]
Thank you!
One more question: where exactly in the code do I need to specify the categories that I need to track?

**Comment by pixeli99** [comment]
You only need to modify JSON annotations. Filter the categories and corresponding annotations you need. You can refer to here.

`https://github.com/open-mmlab/mmtracking/blob/master/tools/convert_datasets/tao/tao2coco.py`
