### ISSUE TITLE
categories index error: list index out of range during testing

### ISSUE THREAD

**Issue by Ares-debugger** [open-mmlab/mmtracking#608]
We train DFF successfully on UAVDT dataset with three categories ('car', 'bus', 'truck'). However, errors is reported during testing:  

---------------------------------------------
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 16580/16580, 43.8 task/s, elapsed: 379s, ETA:     0s
writing results to epoch_7.pkl
Traceback (most recent call last):
  File "tools/test.py", line 225, in <module>
    main()
  File "tools/test.py", line 215, in main
    metric = dataset.evaluate(outputs, **eval_kwargs)
  File "/home/wzq/mmtracking/mmtrack/datasets/coco_video_dataset.py", line 445, in evaluate
    super_eval_results = super().evaluate(
  File "/raid/wzq/env/anaconda3/envs/open-MMTracking/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 641, in evaluate
    result_files, tmp_dir = self.format_results(results, jsonfile_prefix)
  File "/raid/wzq/env/anaconda3/envs/open-MMTracking/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 383, in format_results
    result_files = self.results2json(results, jsonfile_prefix)
  File "/raid/wzq/env/anaconda3/envs/open-MMTracking/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 315, in results2json
    json_results = self._det2json(results)
  File "/raid/wzq/env/anaconda3/envs/open-MMTracking/lib/python3.8/site-packages/mmdet/datasets/coco.py", line 252, in _det2json
    data['category_id'] = self.cat_ids[label]
IndexError: list index out of range
----------------------------------------------
the 'CLASSES' attribution in dataset is {tuple:3} ('car',bus','truck'); the 'cat2label' is {dict:3}{1:0,2:1,3:2} and 'cat_id' is {list:3}[1,2,3]. The testing under debug mode is very slow and the error is reported after the whole testing. Is there some change still to be done? Thank you for answering.

**Comment by Ares-debugger** [comment]
We debug into the function _det2json() of mmdet/coco.py and find that 'for label in range(len(result)'. In ImageNet there are dozens to hundreds categories,  the label won't be out of range mostly. However, when the number of categories is small (like 3), the bbox detected with tiny confident score (e.g., 0.001) will be ranged at a large index (e.g., 10), which will break the evaluation. Thus we filter the detected results by the confident score. Prudently, we make change like this:

data['score'] = float(bboxes[i][4])
if 'val' in self.ann_file:
     if data['score'] < 0.5:  # this operation will filter the bad bboxes.
            continue
data['category_id'] = self.cat_ids[label]
 json_results.append(data)

we use 'val' in self.ann_file because we don't figure out whether this function's work during training. Now the program can be conducted normally, but whether this change is right still need to be considered.

**Comment by pixeli99** [comment]
Hi,

Your question seems to be caused by incorrect `num_classes`. Could you paste the `config` file here?

**Comment by pixeli99** [comment]
https://github.com/open-mmlab/mmtracking/blob/1d26fdb029c7c578d57d7292e88677031cf21d1b/configs/_base_/models/faster_rcnn_r50_dc5.py#L52

**Comment by Ares-debugger** [comment]
Ah, thank you.
