### ISSUE TITLE
 I want to get the loss in the same way as the train step in the validation step

### ISSUE THREAD

**Issue by chromeflute84** [open-mmlab/mmtracking#615]
I'm trying to train SiameseRPN++ with my dataset.
Currently, SiameseRPN++ evaluates to either a success value or eao value.

But, I want to get the loss value after every epoch using validation data, how can I do it?

**Comment by dyhBUPT** [comment]
Hi, you can implement it by modifying the method `evaluate` in **your** `SOTDataset`, e.g., 'https://github.com/open-mmlab/mmtracking/blob/79f8e1946c6e7d071d9d478ff56a6ba1ccbe034c/mmtrack/datasets/base_sot_dataset.py#L273'

Best wishes.

**Comment by chromeflute84** [comment]
Thank you! I'll try it.
