### ISSUE TITLE
How to init wandb logger hook with custom configs?

### ISSUE THREAD

**Issue by ZXYFrank** [open-mmlab/mmtracking#628]

**Comment by dyhBUPT** [comment]
Hi, please refer to mmcv docs https://mmcv.readthedocs.io/en/latest/api.html#mmcv.runner.WandbLoggerHook for details. 
For the wandb init arguments, you can refer to https://docs.wandb.ai/ref/python/init.

Best wishes.

**Comment by ZXYFrank** [comment]
Thanks, I find it. :tada:
write this in the config file 
```python
log_config = dict(
  interval=10,
  hooks=[dict(type='TextLoggerHook'),
         dict(type='WandbLoggerHook',init_kwargs={
             "project":EXP_NAME
         })])
```
