### ISSUE TITLE
When using yolox checkpoints trained from mmdetection, unexpected key in source state_dict

### ISSUE THREAD

**Issue by winterfell2021** [open-mmlab/mmtracking#633]
Hi there, when i try to use my own yolox model checkpoint trained from mmdetection. It reports:
```
unexpected key in source state_dict: ema_backbone_stem_conv_conv_weight, ema_backbone_stem_conv_bn_weight, ema_backbone_stem_conv_bn_bias, ema_backbone_stem_conv_bn_running_mean, ema_backbone_stem_conv_bn_running_var, ....
```

I just modified the num_classes in detector's bbox_head, and every config same with bytetrack_yolox_x_crowdhuman_mot17-private-half.py

**Comment by pixeli99** [comment]
In `mmtrack` and `mmdet`, the key of the model is different, it will be added a prefix `detector` in mmtrack. You can load the PTH file and look at the key in it.

**Comment by winterfell2021** [comment]
> In `mmtrack` and `mmdet`, the key of the model is different, it will be added a prefix `detector` in mmtrack. You can load the PTH file and look at the key in it.

Thanks for your kind reply, I found that its mmdet's feature to store ema in checkpoints, doesn't affect mmtracking training.
