### ISSUE TITLE
Any plans for FairMOT?  (A simple baseline for one-shot multi-object tracking)

### ISSUE THREAD

**Issue by cheng321284** [open-mmlab/mmtracking#65]
The state-of-the-art method for multi-object-tracking, " **FairMOT: On the Fairness of Detection and Re-Identification in Multiple Object Tracking**", *arXiv technical report ([arXiv 2004.01888](http://arxiv.org/abs/2004.01888))*

**Comment by OceanPang** [comment]
Recently we do not have plans to support new methods, but the PRs from the community are welcome.
