### ISSUE TITLE
mAP of every class

### ISSUE THREAD

**Issue by cyy18** [open-mmlab/mmtracking#650]
sorry to bother you. But I want to ask that how can I get mAPof evey class when testing

**Comment by JingweiZhang12** [comment]
You need to delve into COCO API and get it.

**Comment by godwinrayanc** [comment]
Not sure if this works for others but for VID task,you can get the classwise AP by setting `classwise=True` in evaluate function found in the respective dataset under mmtrack/datasets/coco_video_dataset.py

**Comment by cyy18** [comment]
Thanks a lot. If the type of your dataset is 'CocoVideoDataset'. You can get it by setting classwise=True in evaluate function found in the respective dataset under mmtrack/datasets/coco_video_dataset.py. But it will only give you classwise AP with IoU=0.50:0.95. If you want get more, you can go to the lib, find cocoeval.py, then get them
