### ISSUE TITLE
Modifying input channels

### ISSUE THREAD

**Issue by godwinrayanc** [open-mmlab/mmtracking#652]
Hello, I am using a **Resnet-50** with a SELSA VID detector. I want to input a **4-channel** image instead of 3. 

I changed the in_channels in the backbone and got this error.

`RuntimeError: Given groups=1, weight of size [64, 4, 7, 7], expected input[3, 3, 64, 64] to have 4 channels, but got 3 channels instead`

Not sure what else has to be modified. Any tips would be helpful. Thanks!

**Comment by pixeli99** [comment]
In my opinion, if you modify the number of channels of the input data, you should modify the parameters of the subsequent convolution to make the number of channels correspond to each other. Specifically, you can see the shape of each step in the `forward` process. Then customize and modify.

**Comment by godwinrayanc** [comment]
Hello, thanks for the quick reply. I changed the `in_channels` to 4 and  added two parameters in the pipeline
`dict(type='LoadMultiImagesFromFile',color_type='unchanged',to_float32=True)`

Now the model trains but gives **0 mAP** during testing.
