### ISSUE TITLE
About Tracktor

### ISSUE THREAD

**Issue by Leo63963** [open-mmlab/mmtracking#67]
Hi !
Thanks for your sharing. Really admire your work.
Just would like to know, what is the main difference between the original Tracktor++V2 and this reproduction in mmtracking?
From the code, it seems that the tracking (data association) part almost same with original one, but the performance increased a lot in terms of MOTA and IDF1, which is really great.
Therefore, the difference lies in the detector ?
Thanks.

**Comment by OceanPang** [comment]
@Leo63963 Yes, the differences are in the detector. 
There are mainly 2 points:
1. The finetuning behaviors, include the lr and the number of iterations, are different. 
MOT17 is indeed a small dataset that we always suffer from overfitting. We just tune an optimal schedule according to our experiences but not totally follow the one in Tracktor.
2. We do not clip the coordinates outside the image in MOT17. 
This is a trick following the official annotation rules. As the annotations have negative valuables, the detected objects should do in the same way. This behavior greatly increases the recall of the results.

**Comment by Leo63963** [comment]
Hi! @OceanPang 
Thank you so much for your reply.
Best
