### ISSUE TITLE
Which ILSVRC year is used in reported vid performances

### ISSUE THREAD

**Issue by Chop1** [open-mmlab/mmtracking#679]
Hi, the documentation does not specify which version of ILSVRC dataset is used for the training of the vid models.

Would it be ILSVRC 2017 DET and ILSVRC 2017 VID ?

eg this one
![image](https://user-images.githubusercontent.com/22441193/185879020-cce30725-5122-41c6-8a6c-fdbcb3598bd1.png)
![image](https://user-images.githubusercontent.com/22441193/185879215-90453341-9995-4fea-a372-d2479b54ed6e.png)

best

**Comment by dyhBUPT** [comment]
Hi, both VID and DET are used to train the VID model, e.g., DFF.
details in:
https://github.com/open-mmlab/mmtracking/blob/be8a7afbd719b7846a76caca74dd7f331036cdc3/configs/_base_/datasets/imagenet_vid_dff_style.py#L37-L59

**Comment by Chop1** [comment]
Yes I understand. I'm speaking about which version of these dataset is used. Eg 2017, 2015 or others.

**Comment by dyhBUPT** [comment]
2017 is used. You can find it in the REAMD.md as follows:
![image](https://user-images.githubusercontent.com/99722489/185887488-f849ffb8-efcb-4ac5-9089-c280877a813d.png)

**Comment by Chop1** [comment]
https://github.com/open-mmlab/mmtracking/issues/601

In this issue, maintainer claim that the script is not designed to support ILSVRC 2017

**Comment by dyhBUPT** [comment]
yes, you're right.
I've just checked the original data in mmtracking, and ILSVRC 2015 is used.
There seems an error in the README.md, I'll fix it.

sorry. And thx for your issue!
