### ISSUE TITLE
Person id changes when it's viewed from different camera using traktor

### ISSUE THREAD

**Issue by sparshgarg23** [open-mmlab/mmtracking#707]
I was testing the traktor model on some videos and I found that when the camera changes,the id assigned to the object being tracked also changes.
For example if we look at the last few seconds of the below  inference video(obtained by running traktor code),it seems that the runners are now assigned a new ID.
What could be the possible reason,is it because the same person is being viewed from a different camera angle.Or could it be that I need  to retrain the re-id model
dataset used was MOT 20,configuration was  tracktor_faster-rcnn_r50_fpn_8e_mot20-public-half.

Input video
https://drive.google.com/file/d/1IVxcL3a5jUH3huJuyVzgDepIpBE62H3F/view?usp=sharing
inference video
https://drive.google.com/file/d/1Rcl3nrdTQznyPO4GQLm7_juYzsSZtLK4/view?usp=sharing

**Comment by dyhBUPT** [comment]
Hi, I've watched the inference video. It may be caused by the large inter-frame movements, which make the regerssor fail.
It's just a guess, and I suggest you debug to see the actual reason.

Best wishes.

**Comment by sparshgarg23** [comment]
Is there any way we can reduce the inter-frame movement?

**Comment by dyhBUPT** [comment]
We can't reduce the movement of obejcts. But you can try to eliminate the association errors in that case. For example, tuning the threshold of IoU, or add the Kalman Filter.

**Comment by sparshgarg23** [comment]
Hmm,so after the initial associations are made,we can refine them by further sending them to the kalman filter .Did you encounter similar scenarios while working on your research,and if yes what was your way of handling them.
Also,the kalman filter would need to be tuned appropriately such as choosing the motion model correctly because i don't think that when we deal with videos like this,the constant motion/velocity model holds.

**Comment by dyhBUPT** [comment]
1. Yes, you can use Kalman Filter as a additional motion model as you said. The IDSW in MOT is caused by various reasons, so I still suggest you first determine the reason in your case.
2. Kalman Filter is not perfect, but it does work in many scenes. You may need to tune some parameters.

**Comment by sparshgarg23** [comment]
thanks in your work Strong SORT,are you using kalman filters on top of the existing deep learning based models.Could you provide me with some references in which KF is used on top of deep learning based trackers.
of course,goes without saying that i will look into other reasons for id switching

**Comment by dyhBUPT** [comment]
Thanks for you interest in StrongSORT. Unfortunately, most MOT works use the vanilla Kalman Filters with no more modifications.

There are some recent works which optimize some details in Kalman Filter, e.g., [OC-SORT](https://github.com/noahcao/OC_SORT), [BoT-SORT](https://github.com/NirAharon/BoT-SORT). 

Or you can also refer to our previous work, [GIAOTracker](https://github.com/dyhBUPT/GIAOTracker), which propose NSA Kalman and present to use UKF to solve the non-linear problems (but without released codes).

As a reminder, OC-SORT and StrongSORT have been implemented in mmtracking.

Best wishes.

**Comment by sparshgarg23** [comment]
ok will look into those.
