### ISSUE TITLE
What's the develop plan

### ISSUE THREAD

**Issue by kellenf** [open-mmlab/mmtracking#72]
It's a great project, can you share your develop roadmap like mmdetection, so that more people can join in this project and contribute more modern algorithm

**Comment by kellenf** [comment]
just like https://github.com/open-mmlab/mmdetection/issues

**Comment by OceanPang** [comment]
@kellenf Recently we do not have enough developers to support new methods. 
We will add the roadmap once we have the bandwidth to do so.

**Comment by OceanPang** [comment]
A pinned issue has been added.
