### ISSUE TITLE
Is it some code trouble to implement one-stage models using mmtracking?

### ISSUE THREAD

**Issue by ZhiCheng-H** [open-mmlab/mmtracking#721]
I want to use mmtracking to implement some one-stage algorithm. But I observed that the model library don't contain the one-stage tracking model such as FairMOT or JDE. Is it some code trouble to implement these models using mmtracking?

**Comment by pixeli99** [comment]
We have also noticed the problem you mentioned. Most of the existing algorithms are based on TBD paradigm. We may support some algorithms similar to JDE in the future. 😎

**Comment by ZhiCheng-H** [comment]
> We have also noticed the problem you mentioned. Most of the existing models are based on TBD paradigm. We may support some models similar to JDE in the future. 😎

Thanks for your reply and good jobs, I hope this day will come soon.
