### ISSUE TITLE
Why is there no REID module in the original paper in the bytetrack configuration file in MOT? Do I need to add it myself? How should I modify it

### ISSUE THREAD

**Issue by 15689933561** [open-mmlab/mmtracking#738]
Why is there no REID module in the original paper in the bytetrack configuration file in MOT? Do I need to add it myself? How should I modify it？

#mmtracking\configs\mot\bytetrack\bytetrack_yolox_x_crowdhuman_mot17-private-half.py

model = dict(
    type='ByteTrack',
    detector=dict(
        input_size=img_scale,
        random_size_range=(18, 32),
        bbox_head=dict(num_classes=1),
        test_cfg=dict(score_thr=0.01, nms=dict(type='nms', iou_threshold=0.7)),
        init_cfg=dict(
            type='Pretrained',
      checkpoint='C:/Users/Administrator/Desktop/mmtracking/configs/mot/bytetrack/yolox_x_8x8_300e_coco_20211126_140254-1ef88d67.pth' 
        )),
    motion=dict(type='KalmanFilter'),
    tracker=dict(
        type='ByteTracker',
        obj_score_thrs=dict(high=0.6, low=0.1),
        init_track_thr=0.7,
        weight_iou_with_det_scores=True,
        match_iou_thrs=dict(high=0.1, low=0.5, tentative=0.3),
        num_frames_retain=30))
![image](https://user-images.githubusercontent.com/90696813/195497923-27549d65-243c-48a3-8acb-31300e0e9ad7.png)

**Comment by dyhBUPT** [comment]
Hi, ByteTrack doesn't use ReID model on MOT17/MOT20.
