### ISSUE TITLE
In deep sort, the detection box is very accurate, but the tracking sequence number jumps a lot. I need to adjust those parameters (using my own dataset and the public weight used by the reid module)

### ISSUE THREAD

**Issue by 15689933561** [open-mmlab/mmtracking#744]
1.首先我试着将config文件中match_score_thr调大，希望减小reid对跟踪的影响，不大管用
![image](https://user-images.githubusercontent.com/90696813/197132696-137ed718-b2ea-4f4c-94a5-9b8db25b7040.png)
2.然后我试着增加卡尔曼滤波中的预测干扰，希望跟踪结果更倾向于检测值，不大管用

**Comment by pixeli99** [comment]
Hi,

I don't quite understand the meaning of this sentence. `but the tracking sequence number jumps a lot`

Do you mean to say that **ID switching** is very significant？

**Comment by 15689933561** [comment]
> Hi,
> 
> I don't quite understand the meaning of this sentence. `but the tracking sequence number jumps a lot`
> 
> Do you mean to say that **ID switching** is very significant？

yes,it is id switch,i am sorry for my poor english

**Comment by pixeli99** [comment]
Hi,

There are many reasons for ID switching. If you want to weaken the influence of the `reid` module, you can directly use `SORT` or `bytetrack`. I am not sure about the specific situation of your dataset. If it is convenient for you, you can post a sample image here to better identify the problem.
🐱
