### ISSUE TITLE
Question about YouTube-VIS 2019 dataset

### ISSUE THREAD

**Issue by DUT-CSJ** [open-mmlab/mmtracking#754]
Hello, I trained MaskTrack-RCNN on YouTube-VIS 2019 dataset recently.
I get a very close result on validation set compared with model trained by mmtracking.
However, when test the model on validation set, it shows that there are only 8000+ images to be inferenced.
The number to be inferenced (8k+) seems less than the total number of images in validation set. Why is this?
Maybe I don't know enough about this dataset, can anyone answer my question?
Thank you very much!

**Comment by pixeli99** [comment]
Hi,
CSJ,

Are there any logs available? I don't quite understand what you mean. How do you count the number of images?
In my opinion, there should be no such situation. Val data is read without filtering.
