### ISSUE TITLE
How to generate det.txt for making customized MOT format dataset？

### ISSUE THREAD

**Issue by BainOuO** [open-mmlab/mmtracking#757]
After I use the darklabel annotation, only the gt.txt file is available
Looking forward to your reply！

**Comment by dyhBUPT** [comment]
Hi, you need to generate the det.txt with your own detector.

**Comment by BainOuO** [comment]
> Hi, you need to generate the det.txt with your own detector.

Do you mean that I need to label my own dataset to train the detection model, and then use this detection model to generate the det.txt of the image in the video sequence？

**Comment by dyhBUPT** [comment]
> 

Yes, you're right

**Comment by BainOuO** [comment]
> Yes, you're right

thanks!!!

**Comment by meikorol** [comment]
Hi,could you plz give some guidance on customizing dataset and training？
