### ISSUE TITLE
MMTrack requires MMCV>=1.6.1

### ISSUE THREAD

**Issue by Yosshi999** [open-mmlab/mmtracking#758]
**Describe the bug**
Since the commit https://github.com/open-mmlab/mmtracking/commit/d68305a70ee01b0c264fd76436066dc7a3aa2933 , `mmtrack.models` imports `PrRoIPool` in `mmtrack/models/track_heads/mixformer_head.py`, which requires MMCV >= 1.6.1 while [the requirements text](https://github.com/open-mmlab/mmtracking/blob/bb330c2e7bd262dbebc74536b032416f5e9ae595/requirements/mminstall.txt) allows `>=1.3.17`.

**Reproduction**

Dockerfile: 

```Dockerfile
FROM python:3.10.8-bullseye

RUN apt-get update && apt-get install -y libgl1-mesa-dev
RUN pip install torch==1.12.1 torchvision==0.13.1
RUN pip install openmim
RUN mim install mmcv-full==1.5.0

RUN pip install mmdet

RUN git clone https://github.com/open-mmlab/mmtracking.git
RUN cd mmtracking && pip install -r requirements/build.txt && pip install -v -e .
```

Command:

```sh
> docker build -t mmtracking .
> docker run -it --rm mmtracking python -c "import mmtrack.models"
/usr/local/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
/usr/local/lib/python3.10/site-packages/torchvision/models/detection/anchor_utils.py:63: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  /root/pytorch/torch/csrc/utils/tensor_numpy.cpp:68.)
  device: torch.device = torch.device("cpu"),
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mmtracking/mmtrack/models/__init__.py", line 13, in <module>
    from .track_heads import *  # noqa: F401,F403
  File "/mmtracking/mmtrack/models/track_heads/__init__.py", line 2, in <module>
    from .mixformer_head import MixFormerHead, MixFormerScoreDecoder
  File "/mmtracking/mmtrack/models/track_heads/mixformer_head.py", line 7, in <module>
    from mmcv.ops.prroi_pool import PrRoIPool
ModuleNotFoundError: No module named 'mmcv.ops.prroi_pool'
```

**Environment**

```
sys.platform: linux
Python: 3.10.8 (main, Oct 26 2022, 04:42:00) [GCC 10.2.1 20210110]
CUDA available: False
GCC: gcc (Debian 10.2.1-6) 10.2.1 20210110
PyTorch: 1.12.1
PyTorch compiling details: PyTorch built with:
  - GCC 10.2
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=open, BUILD_TYPE=Release, CXX_COMPILER=/opt/rh/devtoolset-10/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-stringop-overflow, LAPACK_INFO=open, TORCH_VERSION=1.12.1, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1
OpenCV: 4.6.0
MMCV: 1.5.0
MMCV Compiler: GCC 10.2
MMCV CUDA Compiler: not available
MMTracking: 0.14.0+bb330c2
```

**Comment by dyhBUPT** [comment]
Thanks for your comments, we'll check it.

**Comment by double-fire-0** [comment]
this error is not been solved now

Traceback (most recent call last):
  File "demo/demo_mot_vis.py", line 9, in <module>
    from mmtrack.apis import inference_mot, init_model
  File "/home/pengmc/wangyan/mmtracking/mmtrack/apis/__init__.py", line 2, in <module>
    from .inference import inference_mot, inference_sot, inference_vid, init_model
  File "/home/pengmc/wangyan/mmtracking/mmtrack/apis/inference.py", line 14, in <module>
    from mmtrack.models import build_model
  File "/home/pengmc/wangyan/mmtracking/mmtrack/models/__init__.py", line 13, in <module>
    from .track_heads import *  # noqa: F401,F403
  File "/home/pengmc/wangyan/mmtracking/mmtrack/models/track_heads/__init__.py", line 2, in <module>
    from .mixformer_head import MixFormerHead, MixFormerScoreDecoder
  File "/home/pengmc/wangyan/mmtracking/mmtrack/models/track_heads/mixformer_head.py", line 7, in <module>
    from mmcv.ops.prroi_pool import PrRoIPool
ModuleNotFoundError: No module named 'mmcv.ops.prroi_pool'


(open-mmlab) pengmc@bnrc-SYS-2029GP-TR:~/wangyan/mmtracking$ pip show mmcv-full
Name: mmcv-full
Version: 1.4.7
Summary: OpenMMLab Computer Vision Foundation
Home-page: https://github.com/open-mmlab/mmcv
Author: MMCV Contributors
Author-email: openmmlab@gmail.com
License: UNKNOWN
Location: /home/pengmc/miniconda3/envs/open-mmlab/lib/python3.7/site-packages
Requires: addict, numpy, opencv-python, packaging, Pillow, pyyaml, yapf
Required-by:

**Comment by Javacr** [comment]
用mmlab的很多仓库，感觉就是兼容性太差了，而且文档中说的兼容版本，很不靠谱
