### ISSUE TITLE
The code is always running in the val epoch, not training.

### ISSUE THREAD

**Issue by Zachein** [open-mmlab/mmtracking#805]
Hello, I want to train the qd-track with the custom datasets. I have run to the 100th epoch and tested it, when I want to continue training,I find that it is all testing from the 101st epoch onwards, I don't know how to solve it.

![image](https://user-images.githubusercontent.com/85224743/208292056-e5798263-3152-4557-b971-49c8336c0690.png)

Best wish! Thank you!

**Comment by dyhBUPT** [comment]
Hi, I can't know the reason from your descriptions. Maybe you should provide some details and your config file.

**Comment by Zachein** [comment]
> Hi, I can't know the reason from your descriptions. Maybe you should provide some details and your config file.

Thanks for your reply. The problem  was caused by an irregular dataset and I have solved it.

**Comment by codeofrina** [comment]
> > Hi, I can't know the reason from your descriptions. Maybe you should provide some details and your config file.
> 
> Thanks for your reply. The problem was caused by an irregular dataset and I have solved it.

I have met the same problem, would you like to share how did you solve it?
