### ISSUE TITLE
about data augmentation and OHEM

### ISSUE THREAD

**Issue by dylan110** [open-mmlab/mmtracking#81]
Thanks for your contribution for the tracking field. But could you provide the code about data augmentation and Ohem version? Thanks a lot!

**Comment by OceanPang** [comment]
Hi @dylan110 , please take a look at this [example](https://github.com/open-mmlab/mmtracking/blob/master/configs/_base_/datasets/mot_challenge.py).

We are using random resize and crop, and color jittering in this config. You can follow this [tutorial](https://mmtracking.readthedocs.io/en/latest/tutorials/data_pipeline.html#) for adding new augmentation pipelines.

For the OHEM to train the detector, please refer to mmdetection and modify the config for the detector accordingly. Here is an [example](https://github.com/open-mmlab/mmdetection/blob/a21eb25535f31634cef332b09fc27d28956fb24b/configs/faster_rcnn/faster_rcnn_r50_fpn_ohem_1x_coco.py).

**Comment by dylan110** [comment]
thanks very much! I try to!
