### ISSUE TITLE
When I customize datasets, I cannot find the file “configs/my_custom_config.py”。

### ISSUE THREAD

**Issue by xxsgh** [open-mmlab/mmtracking#823]
![image](https://user-images.githubusercontent.com/102399568/213218121-4c99f51e-47ea-413e-8ef6-cc7555b388d1.png)

**Comment by pixeli99** [comment]
Hi,
xxsgh,

The file `configs/my_custom_config.py` is just an example. In fact, you can create a new config file.

**Comment by xxsgh** [comment]
> 

thanks！and happy new year！

**Comment by meikorol** [comment]
Have you make custom VID dataset and train it？ I need some guidance
