### ISSUE TITLE
Question about initializing the tracker.

### ISSUE THREAD

**Issue by berkantay** [open-mmlab/mmtracking#83]
Can I start tracking with optional bounding box on a video? If so, should I understand that one shot learning is used for tracking?
Any basic usage document or tutorial would be nice.

Best

**Comment by GT9505** [comment]
Yes, you can use `demo/demo_sot.py` to track with optional bounding box. For the usage document, please refer to [this](https://github.com/open-mmlab/mmtracking/blob/master/docs/quick_run.md#inference-sot-models). 

SiameseRPN++ uses siamese network to tracking the object. And, in my opinion, one shot learning is used for tracking. For more details, please refer to  Section 4.1 and 4.2 in [SiameseRPN](https://openaccess.thecvf.com/content_cvpr_2018/papers/Li_High_Performance_Visual_CVPR_2018_paper.pdf).
