### ISSUE TITLE
Pretrained weight file of MixFormer

### ISSUE THREAD

**Issue by jeongwonryu** [open-mmlab/mmtracking#843]
@songtianhui  
It seems to me that training MixFormer is not yet supported. 
But how are pre-trained model weights like mixformer_cvt_500e_lasot.pth, mixformer_cvt_500e_got10k.pth provided?

**Comment by songtianhui** [comment]
Current pre-trained model weights are modified version from officical MixFormer repository https://github.com/MCG-NJU/MixFormer.
The training code of MixFormer is under construction.
Thanks for your attention!

**Comment by jeongwonryu** [comment]
Can you provide a script for modifying the model weights in the official MixFormer?

**Comment by songtianhui** [comment]
I'm sorry for that it seems that i does not store the script.
It's a little bit dirty work to compare and modify the parameter names in the checkpoint.

**Comment by songtianhui** [comment]
Good news I find it!😂
Script may like:

``` python

def modify_ckpt(ckpt: Dict[str, torch.Tensor]):
    d = {}
    for k, v in ckpt.items():
        if 'score_branch' in k:
            k = k.replace('score_branch.', 'head.score_decoder_head.')
        if 'mlp' in k:
            k = k.replace('fc1.', 'layers.0.0.')
            k = k.replace('fc2.', 'layers.1.')
        if 'box_head' in k:
            k = k.replace('box_head.', 'head.bbox_head.')
            for i in range(4):
                k = k.replace(f'conv{i+1}_br.0.', f'br_corner_pred.{i}.conv.')
                k = k.replace(f'conv{i+1}_br.1.', f'br_corner_pred.{i}.bn.')
                k = k.replace(f'conv{i+1}_tl.0.', f'tl_corner_pred.{i}.conv.')
                k = k.replace(f'conv{i+1}_tl.1.', f'tl_corner_pred.{i}.bn.')
            k = k.replace('conv5_tl.', 'tl_corner_pred.4.')
            k = k.replace('conv5_br.', 'br_corner_pred.4.')
        d[k] = v
    
    torch.save(d, 'mixformer_cvt_mmtrack.pth')
    return d
```

**Comment by jeongwonryu** [comment]
Thanks for your reply!
