### ISSUE TITLE
ValueError: zero-size array to reduction operation maximum which has no identity.

### ISSUE THREAD

**Issue by cupied** [open-mmlab/mmtracking#893]
I am training using my self-created dataset in MMtracking with the script "bytetrack_yolox_x_crowdhuman_mot17-private-half.py". The command I use is: python tools/train.py configs/mot/bytetrack/bytetrack_yolox_x_crowdhuman_mot17-private-half.py.

When running one epoch, I encountered an error: return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity.

Does anyone know what might be causing this issue? Any help would be greatly appreciated.

**Comment by sihaoyu0215** [comment]
How do you solve this problem? Also encounter this.
