### ISSUE TITLE
ModuleNotFoundError: No module named 'mmengine.infer'

### ISSUE THREAD

**Issue by heng94** [open-mmlab/mmtracking#898]
**Describe the bug**

Installation problem

I followed the official document [here](https://mmtracking.readthedocs.io/en/1.x/get_started.html) to install mmtrack 1.0.0rc1.
torch==1.11.0+cu113
mmcv==2.0.0rc1
mmengine==0.1.0
mmdet==3.0.0rc0
mmtrack==1.0.0rc1

After finished the whole installation, I did a test:
```
python demo/demo_mot_vis.py \
    configs/mot/deepsort/deepsort_faster-rcnn-r50-fpn_8xb2-4e_mot17halftrain_test-mot17halfval.py \
    --input demo/demo.mp4 \
    --output mot.mp4
```

It showed an error,
```
from mmengine.infer import BaseInferencer
ModuleNotFoundError: No module named 'mmengine.infer'
```
How to fix this problem? Thank you.

**Comment by DimTrigkakis** [comment]
Same problem. During setup, I saw that a lot of the other modules have been upgraded too much, and so needed to ignore the >= version suggestion (for mmdet, mmcv etc.) and go for the minimal working version with "==" instead for the versions.

mmcls for classification/pretraining did not have a suggestion for version in the installation docs, but I suspected it is similar. Tried with "pip install mmcls==1.0.0rc0" and I can at least run the demo. So in this sense, this was also a package that was upgraded too much by the default installation.

Note : Make sure the deepsort filepath respects "-" vs "_" as there seems to be a tiny inconsistency, you need to manually replace a couple of  '_' in the filename on disk with a couple of '-'

**Comment by lijoe123** [comment]
Thank you so much

> Same problem. During setup, I saw that a lot of the other modules have been upgraded too much, and so needed to ignore the >= version suggestion (for mmdet, mmcv etc.) and go for the minimal working version with "==" instead for the versions.
> 
> mmcls for classification/pretraining did not have a suggestion for version in the installation docs, but I suspected it is similar. Tried with "pip install mmcls==1.0.0rc0" and I can at least run the demo. So in this sense, this was also a package that was upgraded too much by the default installation.
>

**Comment by heng94** [comment]
Thank you. It works.

> Same problem. During setup, I saw that a lot of the other modules have been upgraded too much, and so needed to ignore the >= version suggestion (for mmdet, mmcv etc.) and go for the minimal working version with "==" instead for the versions.
> 
> mmcls for classification/pretraining did not have a suggestion for version in the installation docs, but I suspected it is similar. Tried with "pip install mmcls==1.0.0rc0" and I can at least run the demo. So in this sense, this was also a package that was upgraded too much by the default installation.
> 
> Note : Make sure the deepsort filepath respects "-" vs "_" as there seems to be a tiny inconsistency, you need to manually replace a couple of '_' in the filename on disk with a couple of '-'

**Comment by QianXuna** [comment]
> Same problem. During setup, I saw that a lot of the other modules have been upgraded too much, and so needed to ignore the >= version suggestion (for mmdet, mmcv etc.) and go for the minimal working version with "==" instead for the versions.
> 
> mmcls for classification/pretraining did not have a suggestion for version in the installation docs, but I suspected it is similar. Tried with "pip install mmcls==1.0.0rc0" and I can at least run the demo. So in this sense, this was also a package that was upgraded too much by the default installation.
> 
> Note : Make sure the deepsort filepath respects "-" vs "_" as there seems to be a tiny inconsistency, you need to manually replace a couple of '_' in the filename on disk with a couple of '-'

Thanks.It works!
