### ISSUE TITLE
when I run demo_mot

### ISSUE THREAD

**Issue by Moens007** [open-mmlab/mmtracking#99]
I take a video as input and start reporting errors when it runs to frame 3527:
python demo/demo_mot.py configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py --input /media/moens/Moens/Dataset/school-vedio/01.avi --checkpoint checkpoint/faster-rcnn_r50_fpn_4e_mot17-ffa52ae7\ (1).pth --fps 30 --output mot1.mp4 --show

cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-7m_g9lbm/opencv/modules/video/src/ecc.cpp:572: error: (-7:Iterations do not converge) The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped in function 'findTransformECC'

Can anyone be kind to tell me how to solve this problem?I don't know if it's the problem of my video.
Thanks very much.

**Comment by Moens007** [comment]
I take a video as input and start reporting errors when it runs to frame 3527:
python demo/demo_mot.py configs/mot/tracktor/tracktor_faster-rcnn_r50_fpn_4e_mot17-private.py --input /media/moens/Moens/Dataset/school-vedio/01.avi --checkpoint checkpoint/faster-rcnn_r50_fpn_4e_mot17-ffa52ae7\ \(1\).pth --fps 30 --output mot1.mp4 --show

cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-7m_g9lbm/opencv/modules/video/src/ecc.cpp:572: error: (-7:Iterations do not converge) The algorithm stopped before its convergence. The correlation is going to be minimized. Images may be uncorrelated or non-overlapped in function 'findTransformECC'

Can anyone be kind to tell me how to solve this problem?I don't know if it's the problem of my video.
Thanks very much.

**Comment by OceanPang** [comment]
As we do not have the video that cannot directly debug for you. 

Can you try to figure out where is the bug from and report it here?

**Comment by azaganidis** [comment]
I had the same error when running on videos like EYy1NKyjvlo_000102_000112.mp4 from kinetics test set. There is obviously no correct alignment for those frames, but as a workaround to stop the script from crashing I added try/catch around the findTransformECC function.

**Comment by spk48** [comment]
you should try opencv-python3.4.x

**Comment by yitong-quan** [comment]
> you should try opencv-python3.4.x

Why this can solve the issue above?

**Comment by yitong-quan** [comment]
> you should try opencv-python3.4.x

May I ask, why this can solve the issue above?
